### ISSUE TITLE
npregion_2018-12-27-295x64-2.h5 missed

### ISSUE THREAD

**Issue by VesninEN** [ria-com/nomeroff-net#1]
File npregion_2018-12-27-295x64-2.h5, mentioned in "Hello Nomeroff Net" example missed in folder https://board.ria.ua/models/

**Comment by ApelSYN** [comment]
Thanks for your bugreport, we have renamed this file, I have already corrected everything.
You can download all models at https://nomeroff.net.ua/models/

**Comment by VesninEN** [comment]
Ok, great. Thanks!
