### ISSUE TITLE
Использование GPU приводит к нехватке памяти. Версия v1.0

### ISSUE THREAD

**Issue by nemat-rakhmatov** [ria-com/nomeroff-net#103]
Скачал бета версию и запустил сначала с CPU. Распознавание от 4-7с. Попробовал переключить на GPU.
У меня карта 1060 с 6GB памяти. При запуске demo0 вылетает с ошибкой CUDA error: out of memory при загрузки модели. Попробовал указать tf использовать 1GB памяти, но не помогает. set_memory_growth тоже не помогает.
Я новичок и не знаю что дальше делать. Поможете?

**Comment by ApelSYN** [comment]
6GB должно хватать, примеры из Demo потребляют около 5.5G
```python
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
```
Вот строки для минимизации памяти.

**Comment by nemat-rakhmatov** [comment]
Спасибо, но было меньше: /device:GPU:0 with 5373 MB memory
Смог запустить только установив переменную окружения, export TF_FORCE_GPU_ALLOW_GROWTH=true

Вот этот код из официального документа в принципе должен был сработать, но не получилось

> gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

Ну и другие способы тоже, только переменная окружения сработало.
Ваш код выше, тоже к сожалению не работает.

**Comment by ApelSYN** [comment]
Ok, рад что у вас получилось, про переменную окружения TF_FORCE_GPU_ALLOW_GROWTH буду знать.
