### ISSUE TITLE
Possible typo ".h5s" instead of ".h5"

### ISSUE THREAD

**Issue by devsaider** [ria-com/nomeroff-net#104]
should be
`numberplate_options_2020_10_01_tensorflow_v2_3.h5`
instead of 
`numberplate_options_2020_10_01_tensorflow_v2_3.h5s`?

https://github.com/ria-com/nomeroff-net/blob/e4722f154da29baeaef3e224a2767f02a91fba0e/NomeroffNet/mcm/latest.py#L29

**Comment by ApelSYN** [comment]
Thank you for writing. This is a bug, it has already been fixed.
