### ISSUE TITLE
Тренировка модели Классификатора 

### ISSUE THREAD

**Issue by Chmoqq** [ria-com/nomeroff-net#106]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/ivandaniyelyan/nomeroff-net/train/py/options_train.py", line 41, in <module>
    npClassificator.prepare(PATH_TO_DATASET, verbose=1)
  File "/Users/ivandaniyelyan/nomeroff-net/NomeroffNet/OptionsDetector.py", line 150, in prepare
    self.train_generator = self.compile_train_generator(train_dir, (self.HEIGHT, self.WEIGHT), self.BATCH_SIZE)
  File "/Users/ivandaniyelyan/nomeroff-net/NomeroffNet/OptionsDetector.py", line 347, in compile_train_generator
    imageGenerator.build_data()
  File "/Users/ivandaniyelyan/nomeroff-net/NomeroffNet/Base/ImgGenerator.py", line 49, in build_data
    to_categorical(disc[1], self.labels_counts[1]),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/python/keras/utils/np_utils.py", line 78, in to_categorical
    categorical[np.arange(n), y] = 1
IndexError: index 12 is out of bounds for axis 1 with size 11

Скачал датасет с сайта, запустил и получаю такую ошибку, буду благодарен за помощь

**Comment by ApelSYN** [comment]
Уточните, какую версию датасета вы используете и на кокой версии Nomeroff Net тренируете модель? 
Эта https://nomeroff.net.ua/datasets/autoriaNumberplateOptions3Dataset-2020-10-01.zip ?

**Comment by Chmoqq** [comment]
> Уточните, какую версию датасета вы используете и на кокой версии Nomeroff Net тренируете модель?
> Эта https://nomeroff.net.ua/datasets/autoriaNumberplateOptions3Dataset-2020-10-01.zip ?

Да

**Comment by ApelSYN** [comment]
Вы неответили по версии Nomeroff Net.
Если скрипт ждя тренировки этот https://github.com/ria-com/nomeroff-net/blob/master/train/options.ipynb ,  то у меня на компе все работает нормально, возможно провлема в версии python3, tensorflow или других модулей из https://github.com/ria-com/nomeroff-net/blob/master/requirements.txt

**Comment by Chmoqq** [comment]
> Вы неответили по версии Nomeroff Net.
> Если скрипт ждя тренировки этот https://github.com/ria-com/nomeroff-net/blob/master/train/options.ipynb , то у меня на компе все работает нормально, возможно провлема в версии python3, tensorflow или других модулей из https://github.com/ria-com/nomeroff-net/blob/master/requirements.txt

Версия 1.0

**Comment by Chmoqq** [comment]
> > Вы неответили по версии Nomeroff Net.
> > Если скрипт ждя тренировки этот https://github.com/ria-com/nomeroff-net/blob/master/train/options.ipynb , то у меня на компе все работает нормально, возможно провлема в версии python3, tensorflow или других модулей из https://github.com/ria-com/nomeroff-net/blob/master/requirements.txt
> 
> Версия 1.0

Скрипт options_train.py

**Comment by Chmoqq** [comment]
> Вы неответили по версии Nomeroff Net.
> Если скрипт ждя тренировки этот https://github.com/ria-com/nomeroff-net/blob/master/train/options.ipynb , то у меня на компе все работает нормально, возможно провлема в версии python3, tensorflow или других модулей из https://github.com/ria-com/nomeroff-net/blob/master/requirements.txt

Запустил через Jypyter notebook, заработало, файла для тренировки centermask2 нету в репозитории ?

**Comment by ApelSYN** [comment]
Пока нету. Тренировка скриптов являются частью кода CenterMask2, там есть специальный скрипт который нужно запускать с нужным вам конфигом.
Сами конфиги мы добавили в наш репозиторий:
https://github.com/ria-com/nomeroff-net/tree/master/NomeroffNet/configs/centermask2/numberplates
Мы используем модель из этого конфига centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml, другие конфиги тоже можно использовать, они немного точнее но требуют больших ресурсов памяти GPU и процессорных ядер на GPU.
