### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by lobart** [ria-com/nomeroff-net#112]
Добрый день! При запуске demo0.py выдает такое:
![image](https://user-images.githubusercontent.com/26677576/97544154-3fddd680-19da-11eb-8e82-840f93752685.png)
Tf2.2
lastest.py поменял для tf2.2
Кто сталкивался с такой проблемой?
Спасибо!

**Comment by ApelSYN** [comment]
Сколько у Вас памяти в GPU?

**Comment by lobart** [comment]
@ApelSYN 3433mb
вся информация на картинке
не понимаю, почему не хватает?

**Comment by ApelSYN** [comment]
> @ApelSYN 3433mb
> вся информация на картинке
> не понимаю, почему не хватает?

Нужно около 5G -- Jetson Nano не подойдет, нужен Jetson Xavier NX или Jetson Xavier

**Comment by lobart** [comment]
@ApelSYN у меня стационарник с gtx 1650(на картинке видно)
а почему вы подумали, что у меня Jetson?

**Comment by ApelSYN** [comment]
> @ApelSYN у меня стационарник с gtx 1650(на картинке видно)
> а почему вы подумали, что у меня Jetson?

Невнимательно посмотрел -- такой маленький объем памяти GPU обычно на портативных устройствах, можно отключить  GPU и запустить на CPU, но это работать будет очень меделенно.

**Comment by lobart** [comment]
@ApelSYN 
Понял, а у вас нет конфига и весов поменьше? Для таких бомжей, как я?)

**Comment by ApelSYN** [comment]
> @ApelSYN
> Понял, а у вас нет конфига и весов поменьше? Для таких бомжей, как я?)

Нет, других конфигов нет, мы сами заинтересованы в минимизации объемов потребляемых ресурсов. Можете заапгрейдится до GeForce GTX 1660 6GB 
 GeForce GTX 1660 Super 6GB. Не намного дороже, можно б/у и у вас все заработатет.

**Comment by rm-yakovenko** [comment]
@lobart Модель работает на мобильной GeForce 1050 4GB. 

Попробуйте данное решение https://github.com/ria-com/nomeroff-net/issues/103#issuecomment-705131167

**Comment by lobart** [comment]
@rm-yakovenko у меня такая же карта. С решением, которое вы предложили, заработало, но иногда выдает ошибки о нехватке памяти. 
Какая именно нейронка работает у вас на такой GPU? какой yaml?

**Comment by rm-yakovenko** [comment]
@lobart Вы все еще можете получить ошибки от CUDA о нехватке памяти. Они не должны приводить к падению demo0.py. Ошибки для информации, что необходимо больше GPU RAM. Но при этом сам код работает.

![3d064a100](https://user-images.githubusercontent.com/2056667/97971363-8e6ce580-1dcb-11eb-8f1d-42634d24a2c1.jpg)

Код для теста взят с https://github.com/rm-yakovenko/nomeroff-net-docker
