### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by berkim20** [ria-com/nomeroff-net#115]
![Снимок экрана 2020-12-07 в 19 57 16](https://user-images.githubusercontent.com/33852124/101359577-ac47d180-38c6-11eb-8f0c-6978850e6b4e.png)
День добрый, возникает такая ошибка, в любом из demo. Можете пожалуйста подсказать, как решить?

/Users/azamat/Downloads/nomeroff-net-master/centermask2/centermask/modeling/fcos/fcos_outputs.py:402: UserWarning: This overload of nonzero is deprecated:
	nonzero()
Consider using one of the following signatures instead:
	nonzero(*, bool as_tuple) (Triggered internally at  ../torch/csrc/utils/python_arg_parser.cpp:766.)
  per_candidate_nonzeros = per_candidate_inds.nonzero()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-49dc82a1088f> in <module>
      4 imgs = [mpimg.imread(img_path) for img_path in glob.glob(rootDir)]
      5 
----> 6 cv_imgs_masks = nnet.detect_mask(imgs)
      7 
      8 for img, cv_img_masks in zip(imgs, cv_imgs_masks):

~/Downloads/nomeroff-net-master/NomeroffNet/DetectronDetector.py in detect_mask(self, images, verbose, convex_hull)
     75 
     76             if convex_hull:
---> 77                 masks = [thresh_callback((mask*255).astype(np.uint8)) for mask in masks]
     78             else:
     79                 masks = [cv2.cvtColor((mask*255).astype(np.uint8), cv2.COLOR_GRAY2RGB) for mask in masks]

~/Downloads/nomeroff-net-master/NomeroffNet/DetectronDetector.py in <listcomp>(.0)
     75 
     76             if convex_hull:
---> 77                 masks = [thresh_callback((mask*255).astype(np.uint8)) for mask in masks]
     78             else:
     79                 masks = [cv2.cvtColor((mask*255).astype(np.uint8), cv2.COLOR_GRAY2RGB) for mask in masks]

~/Downloads/nomeroff-net-master/NomeroffNet/DetectronDetector.py in thresh_callback(src_gray, threshold)
     16     canny_output = cv2.Canny(src_gray, threshold, threshold * 2)
     17     # Find contours
---> 18     contours, _ = cv2.findContours(canny_output, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     19     drawing = np.zeros((canny_output.shape[0], canny_output.shape[1], 3), dtype=np.uint8)
     20     # Find the convex hull object for each contour

ValueError: too many values to unpack (expected 2)

**Comment by ApelSYN** [comment]
Судя по всему проблемы с opencv, поробуйте его переустановить, дело в том что не силен в OS Windows, поэтому мне сложно понять что не так.

**Comment by berkim20** [comment]
> Судя по всему проблемы с opencv, поробуйте его переустановить, дело в том что не силен в OS Windows, поэтому мне сложно понять что не так.

Только я не на Windows, а на Mac OS. Спасибо за ответ, правда после переустановки проблема осталась.
