### ISSUE TITLE
Модели, лежащие на сайте, уже натренированы на датасетах?

### ISSUE THREAD

**Issue by berkim20** [ria-com/nomeroff-net#116]
День добрый! Большое спасибо за то, что вы поделились репозиторием!

У меня вопрос, на вашем сайте есть датасеты и уже натренированные модели. Скажите, допустим, модель для распознавания Казахстанских госномеров, она натренирована на датасете, лежащем на вашем сайте? Или в открытом доступе нет модели, на основе Казахстанского датасета?

**Comment by ApelSYN** [comment]
Да есть, они поддягиваются автоматически при первом запуске. Есть конфиг, в котором линки на скачивание моделей:
https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/Base/mcm/latest.py
