### ISSUE TITLE
Ошибка с запуском Hello Nomeroff Net

### ISSUE THREAD

**Issue by Podsohin** [ria-com/nomeroff-net#118]
Здравствуйте. При тесте выдает ошибку и на CPU и на GPU

При установке в файле setup.py убирал 'detectron2'
Устанавливал так для CUDA 10.1
python3 -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.7/index.html
![image](https://user-images.githubusercontent.com/35214218/103396418-c1322080-4b65-11eb-8505-16b9eda7cc81.png)

Подскажите как исправить

**Comment by ApelSYN** [comment]
Попробуйтек собрать с исходников
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'

**Comment by Podsohin** [comment]
Переустановил сервер по новому, выдает такую же ошибку.

при такой установке 
git clone https://github.com/facebookresearch/detectron2.git
python3 -m pip install -e detectron2

выдает такую же ошибку и demo примеры тоже дают ошибку, на сервер CPU такая же ошибка

я использую VM immers.cloud может на виртуальной машине какие то ограничения стоят?
На виртуальной машине можно такое развернуть?

**Comment by ApelSYN** [comment]
Возмодно, ошибка в указании путей. В какой папке запускаете пример? Вносили ли вы уакие-то коррективы в код?

**Comment by Podsohin** [comment]
запускаю в папке nomeroff-net
в код коррективы не вносил.

Скорей всего detectron2 устанавливается криво, там примеры приведены они тоже не работают

**Comment by ApelSYN** [comment]
Нет, предполагается что запуск из папки examples

сб, 2 січ. 2021, 12:00 користувач Sergey <notifications@github.com> пише:

**Comment by Podsohin** [comment]
если запускать из папки examples, ошибка возникает раньше на 27 строке

![image](https://user-images.githubusercontent.com/35214218/103462411-914a6f00-4d57-11eb-9f09-3428ea0dc5f6.png)


Я изначально устанавливал на ноутбуке, вылетала ошибка:
Недопустимая инструкция (стек памяти сброшен на диск)
в интернете нашел ответ: процессор не подходит, стоит у меня core i5 пробовал на ubuntu20 и ubuntu18

арендовал виртуальный сервер  на cpu  и на gpu, ошибки и там и там одинаковые:
 AssertionError: Config file '/home/ubuntu/./NomeroffNet/configs/centermask2/numberplates/centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml' does not exist!

Сегодня на ноутбуке развернул всё на anaconda и получил такую же ошибку что и на сервере 
 AssertionError: Config file '/home/ubuntu/./NomeroffNet/configs/centermask2/numberplates/centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml' does not exist!

Вопрос №1 На ноутбуке это все должно работать или процессор не подходит?

Вопрос №2 на арендованном виртуальном сервере это можно развернуть или нужно копить деньги на свой сервер с платой GPU

**Comment by ApelSYN** [comment]
> если запускать из папки examples, ошибка возникает раньше на 27 строке
> 
> ![image](https://user-images.githubusercontent.com/35214218/103462411-914a6f00-4d57-11eb-9f09-3428ea0dc5f6.png)
> 
> Я изначально устанавливал на ноутбуке, вылетала ошибка:
> Недопустимая инструкция (стек памяти сброшен на диск)
> в интернете нашел ответ: процессор не подходит, стоит у меня core i5 пробовал на ubuntu20 и ubuntu18
> 
> арендовал виртуальный сервер на cpu и на gpu, ошибки и там и там одинаковые:
> AssertionError: Config file '/home/ubuntu/./NomeroffNet/configs/centermask2/numberplates/centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml' does not exist!
> 
> Сегодня на ноутбуке развернул всё на anaconda и получил такую же ошибку что и на сервере
> AssertionError: Config file '/home/ubuntu/./NomeroffNet/configs/centermask2/numberplates/centermask_numberplate_V_39_eSE_FPN_ms_3x.yaml' does not exist!
> 
> Вопрос №1 На ноутбуке это все должно работать или процессор не подходит?
> 
> Вопрос №2 на арендованном виртуальном сервере это можно развернуть или нужно копить деньги на свой сервер с платой GPU

Запускать можно из любой папки, но при этом правильно указывать пути, пример предполагает запуск из папки examples.
Можете указать другой путь с модулю в єтой строке:
NOMEROFF_NET_DIR = os.path.abspath('../')

Также надо правильно указать путь к фото, которое будет поддаваться анализу 
img_path = 'images/example2.jpeg'

На скрине проблема в том что вы устанавливали модуль от пользователя root, а запускаете от другого пользователя и модуль не может скачать модели в заданую папку. "Permission denied" об этом неоднозначно намекает. 

Если вам сложно разобраться с правами доступа запустите скрипт от пользователя root.

**Comment by Podsohin** [comment]
Спасибо огромное!
Получилось настроить
