### ISSUE TITLE
Дообучение centermask2

### ISSUE THREAD

**Issue by arudakov** [ria-com/nomeroff-net#120]
есть ли способ дообучить сабж?
а то определение маски кривое донельзя 
![ed916d213f3ddb4d3f7dcc8b65b2f762](https://user-images.githubusercontent.com/34522310/104625404-c8991400-56a5-11eb-931f-f27e4bc9198c.jpg)

**Comment by ApelSYN** [comment]
Вы просто не поняли как это работает.

Определение маски допускает нахождение зон, которые не являются номером, напрмер это может быть табличка с названием носеленного пункта или другие подходящие для модели области. На первом этапе система находит зоны-кандидаты на распознавание, далее классификатор определяет тип номера, на этом этапе "отсеивается" мусор, такой как на примере.

Способ дотренировать конечно же есть. Берете нашу модель, размечаете свои примеры с помощью [VGG](https://www.robots.ox.ac.uk/~vgg/software/via/) и дотренировуете без проблем, за основу берете этот скрипт https://github.com/youngwanLEE/centermask2#training и тренируете его со своим датасетом

**Comment by arudakov** [comment]
дообучать все равно надо!
вот еще один пример - который мне не нравится....
![ed916d213f3ddb4d3f7dcc8b65b2f762](https://user-images.githubusercontent.com/34522310/104708185-6a644380-572e-11eb-8384-abcac42b5147.jpg)

но за скрипт спасибо!
