### ISSUE TITLE
Rare edge cases

### ISSUE THREAD

**Issue by kurshakuz** [ria-com/nomeroff-net#125]
Hi!

I recently was using your detector for plate extraction from images for further labeling and found that the plate Detector was failing on some images (very rarely). I attached one image as an example. I have tried to find the reason behind that, but was not able to do so. I also tried to see how it works on your demo (in case the problem was on my side) and as you can see it on the attached screenshot, it is not able to detect the plate. Do you have any ideas why that may happen?

Original image:
![160605_8527483](https://user-images.githubusercontent.com/28868430/108949222-374a9380-768e-11eb-8620-10dbe91cd78e.jpg)

Screenshot:
![image](https://user-images.githubusercontent.com/28868430/108949301-5ba67000-768e-11eb-8c34-b99c9ac28d89.png)

**Comment by ApelSYN** [comment]
This error occurs in the operation of the RectDetector.py module. It does not have a good solution at the moment.
We are currently working on a new, much faster, implementation of the numberplate search algorithm, so we will not be able to fix this problem in the near future.
In version 2.0 we will abandon this module.
In addition, the current algorithm does not provide for the recognition of numbers that are written in several lines, so even if the area with the number was set correctly, it still could not be read correctly.

**Comment by kurshakuz** [comment]
@ApelSYN problem is fixed on the new version, I will close the issue.

I would like to ask you if you know the way to handle the multiple line plates? I have seen you OCR model structure and see the the way its LSTM layers are handling independent characters, but see that it is not suited for two line plates. Do you have any ideas where can I look at for handling these types?

**Comment by ApelSYN** [comment]
In version 2.x we already find the location of all lines. The possibility of finding several lines, in the future, will allow the found areas to be glued into one line and recognized on an equal footing with other numbers.
This will be implemented in the next versions of Nomeroff Net
