### ISSUE TITLE
не совсем понял..... теперь мы на gpu не работаем?

### ISSUE THREAD

**Issue by arudakov** [ria-com/nomeroff-net#132]
Traceback (most recent call last):
  File "./get-started-tiny-demo.py", line 35, in <module>
    targetBoxes = detector.detect_bbox(img)
  File "/home/ran/nomeroff-net/NomeroffNet/YoloV5Detector.py", line 79, in detect_bbox
    pred = non_max_suppression(pred)
  File "/home/ran/nomeroff-net/NomeroffNet/../yolov5/utils/general.py", line 465, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
  File "/home/ran/nomeroff-net/venv/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 42, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
RuntimeError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. 'torchvision::nms' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].

**Comment by ApelSYN** [comment]
Вам нужен torch с поддержкой CUDA, в вашей версии такая поддержка очевидно отсутствует.

**Comment by arudakov** [comment]
да ну...

(venv) ran@tatkom-rnd-srv:~/nomeroff-net/examples/py$ python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>>

**Comment by dimabendera** [comment]
Какая у вас версия torch и torchvision?
Для yolov5 необходимо torch>=1.7.1 torchvision>=0.8.2
https://github.com/ria-com/nomeroff-net/blob/master/requirements.txt

**Comment by arudakov** [comment]
все! заработало!
с дуру поставил после req.txt
install python requirments

pip3 install torch==1.7
pip3 install PyYAML==5.3
pip3 install torchvision==0.8
pip3 install Cython
pip3 install numpy
pip3 install -r requirements.txt
