### ISSUE TITLE
OCR model performance and scalability

### ISSUE THREAD

**Issue by azhuchkov** [ria-com/nomeroff-net#134]
As my research showed, **OCR** model works quite good on **CPU** (**~30 ms** per license plate on my laptop), but it behaves **worse** if **GPU** is available (**GeForce GTX 1060 3GB**). It seems that amount of license plates per inference does not matter.

Is it a known limitation or wrong configuration?

I also tried **TensorRT** conversion - latencies **increased** for both CPU and GPU despite of reported graph nodes reduction.

**Comment by dimabendera** [comment]
TensorRT optimizations do not work well with desktop GPUs.
Speed may depend on installed drivers or your GPU may not perform well with Recurrent Layers.
Can you run the command ``nvidia-smi`` during ocr inference and show result?

**Comment by azhuchkov** [comment]
Sorry, I've just made a benchmark that measures **bare** OCR performance - it showed that GPU gives additional **65%** of throughput. Probably my previous results were affected by another model involved.

**TensorRT** showed a little **worse** results without benefits of using GPU.
