### ISSUE TITLE
Не работает админка для разметки датасета.

### ISSUE THREAD

**Issue by Strekalov** [ria-com/nomeroff-net#14]
Добрый день! Перестала работать ваша админка для разметки номеров. 
1) Не генерирует json (изображения используются в формате png)
2) При написании стороннего скрипта, который генерирует json файлы для изображений при нажатии на кнопку save and load next сохраняет сразу все изображения из папки и вешает флаг moderated:1

**Comment by ApelSYN** [comment]
Недавно фиксили баг, возможно что-то пошло не так, п1. ввоспроизводится (пофиксим). По поводу п2.  - у меня все Ok, вышлте пример.
