### ISSUE TITLE
Идеальное изображение

### ISSUE THREAD

**Issue by eab64** [ria-com/nomeroff-net#142]
Здравствуйте!!!
Какие условия для распознавания являются лучшими. По видео делаю скрины в секунду штук 5, потом их распознаю(full_hd)
Есть возможность регулировать любые параметры, яркость, резкость, экспозицию и т.д. Не могу понять почему иногда в неудачных фото, где темно и размыто находит, а в идеальном и четком промах происходит.
Вопрос на что делать акцент при подготовке изображения.
Стоит ли кропать в нужном месте( где предположительно будет номер).

Спасибо!!!

**Comment by SergeyLev** [comment]
Не совсем понятен вопрос, слишком открыто.

У меня отлично работает на живом видео. Номера лучше искать все и сразу за один кадр. Полученые координаты использовать для кропа и отсылать на чтение.

**Comment by eab64** [comment]
> Не совсем понятен вопрос, слишком открыто.
> 
> У меня отлично работает на живом видео. Номера лучше искать все и сразу за один кадр. Полученые координаты использовать для кропа и отсылать на чтение



У вас скорее всего рос.номера, там проблем не было тоже.
У меня кз.номера и там сложно найти тот идеальный угол для 90%+ распознования. Но даже когда нашел, бывает что фото полученное с видео вроде идеальное, но бывает ошибается.

Вот пытаюсь понять что вообще считается идеальным условием для распознования.

**Comment by ApelSYN** [comment]
Без конкретных примеров мы не сможем Вам чем-то помочь, сбросьте те варианты, где воспроизводиться проблема.

**Comment by eab64** [comment]
> Без конкретных примеров мы не сможем Вам чем-то помочь, сбросьте те варианты, где воспроизводиться проблема.

![530R3-](https://user-images.githubusercontent.com/68379504/115225625-1d7a7980-a130-11eb-9267-53ab77703594.jpg)
Допустим вот здесь 
![Снимок экрана от 2021-04-12 17-51-43](https://user-images.githubusercontent.com/68379504/115225680-2d925900-a130-11eb-9df9-baa19420b3fb.png)
Также здесь.
Бывают кадры хуже, но там находится все и вот пытаюсь понять из-за чего иногда возникают ошибки.

**Comment by ApelSYN** [comment]
Неправильно определяется наклон номера. Это можно пофиксить, по ресурсам будет чуть медленнее, придумаем что-нибудь, спасибо за примеры.

**Comment by eab64** [comment]
> Неправильно определяется наклон номера. Это можно пофиксить, по ресурсам будет чуть медленнее, придумаем что-нибудь, спасибо за примеры.

Не за что и спасибо за ответ.

Если будет полезно, то вот под такими углами хороший процент распознований.
![for_git2](https://user-images.githubusercontent.com/68379504/115336300-c1ac0100-a1c0-11eb-915b-ccef0e48de56.jpg)
![for_git](https://user-images.githubusercontent.com/68379504/115336313-ca9cd280-a1c0-11eb-8f82-90c1bb339490.jpg)
![angle3](https://user-images.githubusercontent.com/68379504/115336178-7bef3880-a1c0-11eb-8e36-0147c1d4004f.jpg)

**Comment by SergeyLev** [comment]
Для упрощения задачи без потери скорости, можете попробовать симуляцию OCR.
Обучите yolov4 распознавать отдельные символы, под разными углами. После чего конвертируйте модель в TensorRT.
https://github.com/jkjung-avt/tensorrt_demos#yolov4

**Comment by ApelSYN** [comment]
> yolov4
yolov5 отрабатывает отлично, баудинг бокс с номером определяется коректно. Некорректно проходит нормализация (выравнивание номера), это можно доработать.
