### ISSUE TITLE
textDetector.predict outputs broken text

### ISSUE THREAD

**Issue by kurshakuz** [ria-com/nomeroff-net#143]
After training the OCR using the custom dataset, the test function of the textDetector was able to correctly output the data from images, but for some reason, I have an error during execution of the predict function. Looks like there is some text postprocessing issue, as it seems the number are shown correctly and "-" and "_" are replaced by "X". Notebooks for running and training and sample data jsons are attached. Do you have any ideas how to solve it?

https://gist.github.com/kurshakuz/1f84552e674c0c72bf063213d4b93d4d

![image](https://user-images.githubusercontent.com/28868430/114521710-83fd2480-9c64-11eb-9e05-c4567b9e7d29.png)
![image](https://user-images.githubusercontent.com/28868430/114521760-8c555f80-9c64-11eb-9fc0-4d03ea0e8cb2.png)
![image](https://user-images.githubusercontent.com/28868430/114521794-92e3d700-9c64-11eb-8ca4-d644f19a2f72.png)

**Comment by kurshakuz** [comment]
Интересно, что оба метода в конце вызывают одну и ту же функцию predict внутри OCR.py, тем не менее выход получается разный в завимости от того как инициализируется TextDetector. 
При загрузке подобным образом, аутпут выходит как и ожидается
![image](https://user-images.githubusercontent.com/28868430/114542420-b9f8d380-9c79-11eb-82df-94c1e0395dd0.png)
Но когда хочу запустить процедуру через следующую процедуру, результат получается совсем другой. Может я как то не так его иницилизирую?
f```
rom NomeroffNet.TextDetector import TextDetector
textDetector = TextDetector({...})
textArr = textDetector.predict(zones, regionNames, countLines)
```

**Comment by kurshakuz** [comment]
@dimabendera с нуля перетрейнил используя правильные леттерс, но ошибка выходит вся та же:
https://gist.github.com/kurshakuz/bf28fa2fbb4be046c6f840154958cf83

**Comment by dimabendera** [comment]
Тут скорее нужно было исходить от обратного и просто поменять <b>letters</b> в классе <b>kz</b> при инференсе.
При тренировке мы обьясняем что, letters генерируется автоматичски для датасета.
Если вы передатите в функцию <b>ocrTextDetector.prepare</b> параметр <b>verbose=1</b>
то вы увидете обьяснение для вашего набора данных 
![Screenshot from 2021-04-14 15-37-02](https://user-images.githubusercontent.com/26656535/114711613-d8250900-9d37-11eb-95d7-1eb35c32109d.png)
тут <b>Letters train == Letters val == Letters test </b> 
И этот сгенерённый и отсортированный в алфавитном порядке по датасету <b>Letters</b>  и будет вашим конечным набором <b>letters</b>.
В итоге после тренировки модели стоит только обьявить класс в TextDetectors по примеру https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/TextDetectors/kz.py и использовать его как шаблон в модуле TextDetector или же подгружать как отдельный модуль и использовать

**Comment by kurshakuz** [comment]
Спасибо, проблема решена! Теперь понятно как подгружать модуль отдельно
