### ISSUE TITLE
Cannot import NomeroffNet

### ISSUE THREAD

**Issue by tanpengshi** [ria-com/nomeroff-net#144]
When I am trying to import nomeroffnet, jupyter notebook throws me the following error:

`AttributeError: module 'tensorflow' has no attribute 'ConfigProto'`

How to resolve this issue?

**Comment by ApelSYN** [comment]
В новом tensorflow 2.4.x нету ConfigProto

Вот это коментируем:
```python
# from tensorflow.compat.v1 import ConfigProto
# from tensorflow.compat.v1 import InteractiveSession

# config = ConfigProto()
# config.gpu_options.allow_growth = True
# session = InteractiveSession(config=config)
```
и меняем на, приблизительно, такую конструкцию:
```python
# Specify device
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"
```
также напишите где вы нашли устаревший уод -- мы пофиксим.
