### ISSUE TITLE
Установка и запуск. Docker

### ISSUE THREAD

**Issue by Anzic23** [ria-com/nomeroff-net#145]
Прошу помочь разобраться с системой. Пытаюсь установить в докер. Скопировал папку docker в каталог пользователя, работаю под root (знаю, что лучше так не делать, но система локальная и я готов мериться с рисками). Запустил build-cpu.sh, контейнер создался. Запускаю run.sh получаю ошибку:
```
WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...
```
Пробую запустить такой командой (создал пользователя test1 у которого id 1004:1004):
```
docker run -u 1004:1004 --privileged --rm -it \
   -p 8888:8888 \
   -v `pwd`/..:/var/www/nomeroff-net \
   nomeroff-net
```
Запускается, я попадаю в контейнер с командной строкой. На порту 8888 ничего не происходит. Как дальше работать с системой не соображу. В идеале мне бы распознавать номера с потока камеры и выдавать куда ни будь результат, restfull api - отлично подошел бы. Кто может подсказать, как правильно запустить контейнер, и как с ним работать, пол дня сегодня просидел, так и не получилось победить (.

**Comment by ApelSYN** [comment]
Надо доустановить jupyter notebook и его запустить
```
pip3 install jupyter
jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root
```
Просто не всем это нужно, можно запустить все с консоли на чистом python3

**Comment by alexeysi** [comment]
Тоже хотел собрать на своём выделенном сервере на виртуальной машине... Вроде Тоже собрал на докере запустил build-cpu.sh, попал в командную строку. Как и писали поставил jupyter. Зашёл ввёл токен...Открыл getting-started-tiny-demo прилетает какой-то warning нет GPU...

В идеале было-бы приятно если бы разработчики просто поделились образом виртуалки Fedora для чтобы можно было быстро поднять приблизительно такой же сервер как у вас на https://nomeroff.net.ua 
Отправил POSTом картинку получил в JSON результат....

**Comment by ApelSYN** [comment]
Вот так запускать на CPU (в коментах писал, да кто же их читает):
```
# Specify device
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "0" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""  # For CPU inference
# os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"
```
Система запущена не на виртуалке а в docker-контейнерах для Kubernetes (это разновидность частного облака). Мы не выкладываем наши наработки т.к. это глубоко интегрированная система с нашими сервисами, которая разбита внутри на микросервисную архитектуру, одни микросервисы ищут маску номера, другие распознают, есть избыточность инстансов для обеспечения надежности и стабильности.
