### ISSUE TITLE
Планы на будущее.

### ISSUE THREAD

**Issue by yope-dev** [ria-com/nomeroff-net#147]
Планируете ли вы сделать решенее для процессоров arm. Лично для меня скорость не имеет значение только точность и то, запуститься ли на ARM

**Comment by ApelSYN** [comment]
У меня на arm на jetson xavier все работает, просто отключаю GPU. Работает, конечно, медленнее, ядра нагружпбтся на 100%, но все примеры запускаются.
А какие у вас проблемы?

**Comment by yope-dev** [comment]
> У меня на arm на jetson xavier все работает, просто отключаю GPU.
> 
> ```python
> # Specify device
> import os
> os.environ["CUDA_VISIBLE_DEVICES"] = "" 
> # os.environ["CUDA_VISIBLE_DEVICES"] = ""  # For CPU inference
> # os.environ["TF_FORCE_GPU_ALLOW_GROWTH"]="true"
> ```
> 
> Работает, конечно, медленнее, ядра нагружаются на 100%, но все примеры запускаются.
> 
> А какие у вас проблемы?

Проблемы на этапе установки tensorflow, если я правильно понимаю мне нужно скомпилировать под arm TF-lite

**Comment by ApelSYN** [comment]
> Проблемы на этапе установки tensorflow, если я правильно понимаю мне нужно скомпилировать под arm TF-lite

Нет, я ставлю полноценный tf 2.4.1, для корректной работы моделей OCR. Его можно собрать самому (это очень долго, даже на jetson xavier или взять уже собраный).

Другое дело если у вас очень мало ОЗУ и tf не запусается, тогда я не знаю чем Вам помочь.

**Comment by yope-dev** [comment]
> > Проблемы на этапе установки tensorflow, если я правильно понимаю мне нужно скомпилировать под arm TF-lite
> 
> Нет, я ставлю полноценный tf 2.4.1, для корректной работы моделей OCR. Его можно собрать самому (это очень долго, даже на jetson xavier или взять уже собраный).
> 
> Другое дело если у вас очень мало ОЗУ и tf не запусается, тогда я не знаю чем Вам помочь.

Очень странно
`test@orangepipcplus:~$ pip3 install tensorflow>=2.3.*
ERROR: Could not find a version that satisfies the requirement tensorflow
ERROR: No matching distribution found for tensorflow`

**Comment by yope-dev** [comment]
Если нужно кому-то установить  [TF на armhf](https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-pi-4.html)
