### ISSUE TITLE
Утечка памьяти

### ISSUE THREAD

**Issue by yope-dev** [ria-com/nomeroff-net#150]
Сделал два скрипта.
`server.py`, `client.py`
Общение через сокет, в server.py отдельные потоки обрабатывают запросы все бы хорошо но течет памьят.
Если через CUDA то видеопамьят если на проце то ОЗУ. В простое памьят не течет (если нету запросов от `client.py` на `server.py`)
Может ли быть это проблемой ваших скриптов?

### p.s
Если нужно что-то скинуть то скину

**Comment by ApelSYN** [comment]
Проблема однозначно есть, виновник библиотека CRAFT ( https://github.com/clovaai/CRAFT-pytorch ), которая используется для детекции надписей внутри найденного баундинг бокса.
Если номер сфоткан под углом, без нее не обойтись :(
К сожалению, я не готов дебажить CRAFT, мы присматриваемся к альтернативам. Можете перейти на старую версию 1.1, она менленее, но там CRAFT не используется.

**Comment by yope-dev** [comment]
> Проблема однозначно есть, виновник библиотека CRAFT ( https://github.com/clovaai/CRAFT-pytorch ), которая используется для детекции надписей внутри найденного баундинг бокса.
> Если номер сфоткан под углом, без нее не обойтись :(
> К сожалению, я не готов дебажить CRAFT, мы присматриваемся к альтернативам. Можете перейти на старую версию 1.1, она менленее, но там CRAFT не используется.

Окей, спасибо Вам большое, надеюсь в будущем Вы или может кто-то исправите и все будет работать еще быстрее и лучше. Желаю Вам успехов и поменьше багов. Еще раз спасибо
