### ISSUE TITLE
Конфликт зависимостей

### ISSUE THREAD

**Issue by nickfaces** [ria-com/nomeroff-net#167]
На Ubuntu 20.04 не удается собрать, тк конфликтуют tensorflow и nomeroff-net в плане того какая версия numpy им нужна

Tensorflow просит =1.19.2, а устанавливается 1.21

**Comment by ApelSYN** [comment]
Поставте ту что нужна для  TensorFlow

ср, 14 лип. 2021, 11:17 користувач nickfaces ***@***.***>
пише:
