### ISSUE TITLE
ImportError: cannot import name 'time_synchronized'

### ISSUE THREAD

**Issue by opengs** [ria-com/nomeroff-net#168]
Сделал Docker Image на версии 2.1. Время от времени есть именения в ветке и что-то слетает. Вчера делал image без кеша и удалил volume где была библиотека. Не работает. Не могу разобраться как пофиксить...

Перейти на новую версию не могу потому что я на Nvidia Xavier и Dockerfile на 200 строк

```
git clone -b v2.1 https://github.com/ria-com/nomeroff-net.git /data/lib
cd /data/lib/examples/py
python3 get-started-tiny-demo.py
```
```
Traceback (most recent call last):
  File "get-started-tiny-demo.py", line 17, in <module>
    from NomeroffNet.YoloV5Detector import Detector
  File "/data/lib/NomeroffNet/__init__.py", line 6, in <module>
    from .YoloV5Detector import *
  File "/data/lib/NomeroffNet/YoloV5Detector.py", line 23, in <module>
    from utils.torch_utils import select_device, load_classifier, time_synchronized
ImportError: cannot import name 'time_synchronized'
```

**Comment by opengs** [comment]
Прогрузки библеотек в реальном времени очень проблематичны. Ести ли в планах перейти например на gitmodules?

**Comment by opengs** [comment]
Ок. Вчера были изминения в yolov5, а у Вас clone на master. Можно откатить yolo5 до комита 9dd33fd20f0f1a07762df129d2c2da2b1e9d09d7 и заработает.

**Comment by ApelSYN** [comment]
Фукция time_synchronized в NomeroffNet/YoloV5Detector.py не используется. Ее можно убрать, в новой версии пофиксим
