### ISSUE TITLE
Проблема с запуском demo

### ISSUE THREAD

**Issue by MattFrKPI** [ria-com/nomeroff-net#17]
Не хочу показаться идиотом, но при запуске выдает нечто следующее:

  File "h5py\h5f.pyx", line 85, in h5py.h5f.open

OSError

Пол интернета облазал, так и не понял из-за чего это. Есть возможность помочь?

**Comment by dimabendera** [comment]
Посмотрите эту issue https://github.com/keras-team/keras/issues/6221.
