### ISSUE TITLE
Подготовка номерных знаков | Обучение классификатора

### ISSUE THREAD

**Issue by InzGIBA** [ria-com/nomeroff-net#170]
Добрый день.

Возник вопрос, в проекте имеется ли утилита, которая позволяет вырезать из фотографий номерные знаки, для подготовки датасета?
Или же стоит воспользоваться примерами для написании своего?

**Comment by alexeysi** [comment]
Да вроде все в пару строчек приватно на основании примера это делают под свой случай...

**Comment by alexeysi** [comment]
Имейте в виду что при обработке датасета нужно вначале распознавать, потом нормализовать(размер и wrap) потом записывать. Для обучения нужны именно нормализованные номера.

**Comment by alexeysi** [comment]
А вообще смотрите https://github.com/ria-com/nomeroff-net/blob/v2.3/tools/avto-nomer-tool/py/avto-nomer_grab2.ipynb
