### ISSUE TITLE
Upload users runtime-test.py results to RIA-COM HTTP server Database

### ISSUE THREAD

**Issue by aliansplastby** [ria-com/nomeroff-net#195]
Upload current git tag and branch, lscpu,nvidia-smi and benchmark results log to ria hosted HTTP server....

**Comment by aliansplastby** [comment]
### AMD 5950X + NVIDIA TITAN XP 12Gb v2.5branch
Processed 310 photos
Time 19.29887890815735
One photo process 0.06225444809083016 seconds

image_load_time_all 4.841108322143555; 0.015616478458527596 per one photo
detect_bbox_time_all 2.8100597858428955; 0.009064708986589986 per one photo
craft_time_all 9.18262267112732; 0.029621363455249416 per one photo
perspective_align_time_all 0.7033400535583496; 0.0022688388824462892 per one photo
classification_time_all 0.7522878646850586; 0.0024267350473711567 per one photo
ocr_time_all 0.9932823181152344; 0.0032041365100491433 per one photo

**Comment by aliansplastby** [comment]
### AMD 5950X + NVIDIA GTX 960 4Gb v2.5branch
Processed 310 photos
Time 42.08067226409912
One photo process 0.1357441040777391 seconds

image_load_time_all 4.826970100402832; 0.015570871291622039 per one photo
detect_bbox_time_all 4.827017784118652; 0.015571025110060168 per one photo
craft_time_all 29.817101001739502; 0.09618419677980485 per one photo
perspective_align_time_all 0.7102460861206055; 0.002291116406840663 per one photo
classification_time_all 1.4783849716186523; 0.0047689837794150074 per one photo
ocr_time_all 0.40520477294921875; 0.0013071121708039314 per one photo

**Comment by ApelSYN** [comment]
Спасибо за информацию, мы можем добавить ваши замеры в v2.5. Только, я хочу попросить вас обновить код Nomeroff Net до последних изминений ветки v2.5 и сделать замеры повторно, т.к. мы сделали ряд обновлений и пофиксили некоторые баги. Скорее всего время незначительно увеличиться.
Thanks for your benchmarks, we can add your measurements in v2.5. Only, I want to ask you to update the Nomeroff Net code to the latest changes in the v2.5 branch and make the measurements again, because we made a number of updates and fixed some bugs. Most likely, the time will increase slightly.

**Comment by aliansplastby** [comment]
###AMD 5950X + NVIDIA TITAN XP 12Gb v2.5branch TAG e03f895
Существенно увеличилась скорость Craft -50%
detect_bbox_time -20%

Processed 310 photos
Time 13.897008419036865
One photo process 0.04482905941624795 seconds

image_load_time_all 4.69725775718689; 0.015152444378022224 per one photo
detect_bbox_time_all 2.2929203510284424; 0.007396517261382072 per one photo
craft_time_all 4.470111846923828; 0.014419715635238155 per one photo
perspective_align_time_all 0.7009255886077881; 0.0022610502858315747 per one photo
classification_time_all 0.7474820613861084; 0.0024112324560842204 per one photo
ocr_time_all 0.9838879108428955; 0.003173831970460953 per one photo

###AMD 5950X + 3060TI LHR v2.5branch TAG e03f895
Processed 310 photos
Time 14.091116189956665
One photo process 0.04545521351598924 seconds

image_load_time_all 4.798529863357544; 0.015479128591475948 per one photo
detect_bbox_time_all 2.460993528366089; 0.007938688801180932 per one photo
craft_time_all 4.525857448577881; 0.014599540156702841 per one photo
perspective_align_time_all 0.7003147602081299; 0.0022590798716391287 per one photo
classification_time_all 0.703162670135498; 0.002268266677856445 per one photo
ocr_time_all 0.8927915096282959; 0.00287997261170418 per one photo

**Comment by aliansplastby** [comment]
[BENCHMARK RESULTS](https://docs.google.com/spreadsheets/d/1Rc25oZPKnxnLXhPtC2e_mACbL-nUKeTqidl4sFN34R8/)

Could somebody make a code review?
[benchmark_gsheets.tar.gz](https://github.com/ria-com/nomeroff-net/files/7730339/benchmark_gsheets.tar.gz)

**Comment by alexeysi** [comment]
[benchmark_gsheets_v2.zip](https://github.com/ria-com/nomeroff-net/files/7810736/benchmark_gsheets_v2.zip)
V2 includes support of CPU detect both on Windows and Linux

**Comment by alexeysi** [comment]
???WINDOWS/LINUX RESULTS 1.5X PERFORMANCE DIFFERENCE????

<google-sheets-html-origin><meta name="sheets-banding" data-sheets-range="A1:S19" data-sheets-banding-properties="{&quot;1&quot;:{&quot;1&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:12434877}},&quot;2&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:16777215}},&quot;3&quot;:1,&quot;4&quot;:{&quot;4&quot;:{&quot;1&quot;:2,&quot;2&quot;:15987699}},&quot;5&quot;:1}}"><style type="text/css"></style>

git TAG | Graphics Card | Torch+Cuda | CPU | Total photos | Total time
-- | -- | -- | -- | -- | --
4f969d3 | NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB | 1.10.1+cu113 | AMD Ryzen 7 5800H with Radeon Graphics 1Sx8Cx2T 3201Ghz | 310 | 24,25
4f969d3 | NVIDIA GeForce RTX 3070 Laptop GPU, 7957MiB | 1.10.1+cu113 | AMD Ryzen 7 5800H with Radeon Graphics 1Sx8Cx2T 3200,0000Ghz | 310 | 17,58
