### ISSUE TITLE
ImportError: cannot import name 'imgproc' from 'craft_mlt'

### ISSUE THREAD

**Issue by GunGraveGH** [ria-com/nomeroff-net#197]
Здравствуйте, пробую запустить демки из папки Examples.

Возникает ошибка - ImportError: cannot import name 'imgproc' from 'craft_mlt' (unknown location)

![image](https://user-images.githubusercontent.com/40600793/147962238-a7fac9d7-0113-4491-baac-6d57234fb1ae.png)

Мои шаги установки

1) клонировал репозиторий 
git clone https://github.com/ria-com/nomeroff-net.git

2) pip3 install -r requirements.txt  

3) Загрузил модели и положил в папку nomeroff-net\data\models 

4) установил torch с поддержкой cuda
pip install torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

пробовал разные версии torch (без cuda, cuda 10.1, 10.2)

ОС - Windows 10
Установлена одна версия Python - 3.9.1
CUDA 10.1
Nvidia GTX 1050ti

**Comment by alexeysi** [comment]
А в папке /data/repos/NpPointCraft есть craft_mlt?

**Comment by GunGraveGH** [comment]
Есть data\repos\NpPointsCraft\craft_mlt\CRAFT-pytorch.git

**Comment by alexeysi** [comment]
нормально mcm.py его значит клонировал при запуске но пути не видны и не прописались... тут дело похоже в том что на windows никто особо не тестировал... мне кажется тут все в linux'e)
Запустите python3 test.py в папке craft_mlt должно выдать - "torch.Size([1, 384, 384, 2])"

**Comment by alexeysi** [comment]
по куде ставьте  11.3. Я работаю с branch v2.5 и он на cuda 10.1 точно не работает

pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio===0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html

**Comment by alexeysi** [comment]
Ну и yolov5 можете отдельно проверить что работает запустив папке yolov5 python3 detect.py
Результаты будут в runs/detect/exp

**Comment by GunGraveGH** [comment]
вывод с python test.py ->

Loading weights from checkpoint (weights/craft_mlt_25k.pth)
Traceback (most recent call last):
  File "D:\Worksheet\nomeroff-net\data\repos\NpPointsCraft\craft_mlt\CRAFT-pytorch.git\test.py", line 128, in <module>
    net.load_state_dict(copyStateDict(torch.load(args.trained_model)))
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 579, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\Users\Mike\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'weights/craft_mlt_25k.pth'

скачал веса, положил в папку weights, после этого выполнился успешно

ошибка ImportError: cannot import name 'imgproc' from 'craft_mlt' осталась

далее разобрался:

у меня структура папок была следущая 
data\repos\NpPointsCraft\craft_mlt\CRAFT-pytorch.git\

если перенести все из папки CRAFT-pytorch в корень craft_mlt ошибка пропадает

все работает

Спасибо за помощь!

P.S
с линуксом не особо дружу)
в организации где работаю нужно было на парковку распознавание номеров сделать
я виндовое приложение написал на версии Nomeroff-net 2.3
В C# через pythonnet модули подгружаю

крутится уже месяца 4, полет нормальный
на gtx 1050ti ~16 fps на детектировании номера и ~3-5 fps на распознавание
разрешение камеры 2560x1440 (на распознавание ~40% сцены уходит)
CUDA 10.1

Сейчас новую версию опробую)

**Comment by alexeysi** [comment]
Использую аналогично, рекомедую переключится с мастера на branch v2.5 и запустить web rest сервер.

Странно это все, веса должны были сами скачиваться нормально.

**Comment by alexeysi** [comment]
ISSUE #195 
https://docs.google.com/spreadsheets/d/1Rc25oZPKnxnLXhPtC2e_mACbL-nUKeTqidl4sFN34R8/

По скорости работы есть большая зависимость не только от gpu, но и от CPU. Результаты на 5950x и epyc на 3.5ггц существенно разнятся на одинаковой карте.

**Comment by GunGraveGH** [comment]
клонировал branch v2.5 
работает без всяких манипуляций
get-started-demo без ошибок на CUDA 10.1
