### ISSUE TITLE
TextDetector from the image of LP 

### ISSUE THREAD

**Issue by AzimovS** [ria-com/nomeroff-net#20]
Если у меня есть фотка только номеров автомобиля, можно ли его как-то проверить на ваших алгоритмах?  Просто ваш алгоритм не находит номера (из-за плохого качества картинки). Хотелось бы проверить как он определит текст, если будет только фотка номеров. 

Здесь можно увидеть какие именно картинки были использованы
https://github.com/AzimovS/LPDetection/blob/master/demo3.ipynb

**Comment by AzimovS** [comment]
UPD. Картинки должно быть jpg или же jpeg. Почему-то если картинка в формате в png, то он не детектит номера.

**Comment by AzimovS** [comment]
Еще один вопрос. Если посмотреть на аутпут https://github.com/AzimovS/LPDetection/blob/master/demo.ipynb, то качество сильно падает и уменьшается точность распознавание, можете подсказать как избежать падения качества?

**Comment by dimabendera** [comment]
Если речь идёт о видеокамере, то лучшим вариантом было бы обучать сеть под каждую камеру отдельно, это бы значительно улучшило качество нахождения. Так же много зависит от того как настроить саму камеру.
Хотел бь уточнить какого размара исходные изображения?
Думаю качество сильно улучшится если вы натренируете модель на данных с видеокамер.

**Comment by AzimovS** [comment]
Спасибо за ответ тоже так думал сделать. Размер начального изображения 1200x1600. Дальше я вырезал оттуда машины.
