### ISSUE TITLE
Ошибки при тесте

### ISSUE THREAD

**Issue by AzimovS** [ria-com/nomeroff-net#21]
Когда хочу натренировать свою модель встречается такая проблема
![image](https://user-images.githubusercontent.com/35425540/58933600-a7620900-8789-11e9-830a-a3dc53c100d3.png)

Дальше я просто попытался протестить на вашей готовой модели Для удобства я загрузил только две фотки. Вот здесь можно увидеть
https://github.com/AzimovS/LPDetection/blob/master/ocr-kz.ipynb что в 5 блоке выходит та же ошибка.Можете подсказать из-за чего возникает данная ошибка?

**Comment by dimabendera** [comment]
Ошибка возникает из за несоответсвия размера Batch и количества изображений. У нас стандартно batch стоит 32 картинки, а у вас всего 2. Попробуйте дописать как то так:

```python
class kz(OCR):
    def __init__(self):
        OCR.__init__(self)
        self.letters = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "E", "H", "I", "K", "M", "O", "P", "T", "X"]
        self.EPOCHS = 3

        #Измините тут
        self.BATCH_SIZE = 22
```
Или попробуйте добавить в тестовую выборку изображений

**Comment by AzimovS** [comment]
Сейчас пытаюсь натренировать с помощью новых данных.  Я подправил датасет сейчас в train 1120 картинок, в val 1056 и в test 64 (Я понимаю, что распределил не очень, но сейчас цель хотя бы начать тренировать). Как видите все кратно 32, но все еще возникает та же ошибка.

**Comment by AzimovS** [comment]
в TextImageGenerator стоит эта линия, ```if ext == '.png':``` Хотя все мои картинки в формате jpg
