### ISSUE TITLE
Отсутствие моделей

### ISSUE THREAD

**Issue by fallenfallen** [ria-com/nomeroff-net#22]
Отсутствуют OCR модели для украинских номеров под cpu anpr_ocr_ua_12-cpu.h5

**Comment by ApelSYN** [comment]
Эти уже устарели, беиите свежие
https://nomeroff.net.ua/models/ocr/ua/

нд, 9 черв. 2019, 19:09 користувач fallenfallen <notifications@github.com>
пише:

**Comment by fallenfallen** [comment]
Да, но там только под gpu

**Comment by ApelSYN** [comment]
Как-то упустили из виду, действительно для CPU мы новых не натренировали. Я добавил на сайт cpu anpr_ocr_ua_12-cpu.*

**Comment by fallenfallen** [comment]
Спасибо большое)
