### ISSUE TITLE
Распознавание номеров для Молдовы

### ISSUE THREAD

**Issue by ciolak** [ria-com/nomeroff-net#222]
Не могли бы добавить в функционал распознавание молдавских номеров. Сейчас процент определения низкий, где то на уровне 50%.
Долго пробовал своими усилиями дотренировать модель, не получилось (новичок в машинном обучении).
Собрал 1000 изображений с номерами [ссылка](https://disk.yandex.ru/d/giKmpw-GpPAMIQ)

**Comment by alexeysi** [comment]
А много еще на улице машин с номерами образца 1992 года? Или больше с 2015? Есть в принципе минимальная база 20 тыс 1992го и 10тыс 2015го. 1000 изображений конечно недостаточно.

**Comment by ApelSYN** [comment]
Спасибо за датасет. Мы можем натренировать модель, но нам нужны для этого данные. 1000 это хорошее начало, но этого мало, для хорошего качества модели нужно где-то 10 000 или больше. Их можно спарсить с других сайтов, собрать самому или купить (например на этом сайте https://platesmania.com/md/). Я не знаю какие сейчас цены, раньше был минимальный заказ 50$ за 50 000 фото.
Потом этот датасет надо будет "обработать" и извлечь сами номера (это тоже можем сделать мы), после этого можно будет добавлять модель md в nomeroff.net .
Мы заинтересованы в поддержке новых стран но на сбор датасета времени нет, тут Вы можете внести свой вклад данными.

**Comment by ciolak** [comment]
> А много еще на улице машин с номерами образца 1992 года? Или больше с 2015? Есть в принципе минимальная база 20 тыс 1992го и 10тыс 2015го. 1000 изображений конечно недостаточно.

Нет не много, но встречаются. В основном с 2015 года. И в Молдове есть еще так скажем переходные с 2011 - 2015. [Wiki](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B7%D0%BD%D0%B0%D0%BA%D0%B8_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D1%8B%D1%85_%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2_%D0%B2_%D0%9C%D0%BE%D0%BB%D0%B4%D0%B0%D0%B2%D0%B8%D0%B8)


> 1000 это хорошее начало, но этого мало, для хорошего качества модели нужно где-то 10 000 или больше.

Если я правильно понял, то мы можем разделить процесс на 2 части. 
1. Вы заносите MD в nomeroff.net (используя отправленные 1000 фото) а я в это время собираю полный датасет для финальной тренировки. 
2. Прогоняется повторно на базе 10к фото?

**Comment by ApelSYN** [comment]
> Если я правильно понял, то мы можем разделить процесс на 2 части.
> 
> Вы заносите MD в nomeroff.net (используя отправленные 1000 фото) а я в это время собираю полный датасет для финальной тренировки.
> Прогоняется повторно на базе 10к фото?

Мы не можем добавить некачественную модель в репозиторий. План такой: вы даете датасет 10 000+ и мы тренируем и добавляем md c хорошим качеством, вы присылаете проблемные фото мы фиксим проблемы. Сами "вырезанные" из датасета номера выкладываем в общий доступ, как это сделано для других стран. Сам датасет с фото авто не выкладываем. В датасете в описании указываем Вас как автора этого набора данных.
"Квадратные/многолинейные номера" нету смысла присылать, они распознаются однолинейной моделью и распознаються хуже. Это плата за простоту и за скорость.

**Comment by ciolak** [comment]
Понял, спасибо. Подготовлю нужный датасет и вернусь.

**Comment by ciolak** [comment]
Собрал датасет в 12500 фотографий [ссылка](https://disk.yandex.ru/d/g8Us5Ts_wNmm_Q), должно хватить для тренировки

**Comment by ciolak** [comment]
Вчера написал Вам на почту, моя почта ciolak@mail.ru
