### ISSUE TITLE
Вырезание номеров из фото

### ISSUE THREAD

**Issue by SergeKZ** [ria-com/nomeroff-net#244]
Хочу дообучить номера подскажите какой скрипт отвечает за выдерание номеров из картинок?
На хабре нашел инструкцию но она устарела =(

**Comment by ApelSYN** [comment]
Вот тут пример:
https://github.com/ria-com/nomeroff-net/blob/master/examples/ju/dataset_tools/auto_number_grab.ipynb

Там предполагается что есть некий csv-файл, в котором указан файл без расширения и что написано на номере, приблизительно так:
```csv
photoId,npText
250031471orig,NEBV043
```
Но если этой информации нет, можно универсальной моделью попытаться задетектить, тогда этот файл не указываем, вот пример формирования датасета для Молдовы:
```python
auto_number_grab(root_dir, res_dir, image_loader="turbo",
                 replace_template={'moderation': {'isModerated': 1, 'moderatedBy': 'RIA.com'}, 'state_id': 2},
                 #csv_dataset_path=csv_dataset_path, # or None if you don`t have moderated data
                 prisets={
                     "eu": {
                         "for_regions": ["eu"],
                         "model_path\": "latest"
                     },
                 },
                 default_label = "eu",
                 quality_profile=[5, 2, 0])
```
там грамматическая ошибка prisets (правильно presets), но пока что это не пофиксили, поэтому пишем "prisets"

**Comment by SergeKZ** [comment]
Спасибо буду пробовать, наверно пример с csv подойдет ибо фото вида 777AAA01.jpg придется просто листинг кинуть в csv

**Comment by SergeKZ** [comment]
Спасибо буду пробовать, наверно пример с csv подойдет ибо фото вида 777AAA01.jpg придется просто листинг кинуть в csv

**Comment by SergeKZ** [comment]
> Вот тут пример: https://github.com/ria-com/nomeroff-net/blob/master/examples/ju/dataset_tools/auto_number_grab.ipynb
> 
> Там предполагается что есть некий csv-файл, в котором указаны имена файлов без расширения и что текст на номере, приблизительно так:
> 
> ```
> photoId,npText
> 250031471orig,NEBV043
> ```
> 
> Но если этой информации нет, можно универсальной моделью попытаться задетектить, тогда этот файл не указываем, вот пример формирования датасета для Молдовы:
> 
> ```python
> auto_number_grab(root_dir, res_dir, image_loader="turbo",
>                  replace_template={'moderation': {'isModerated': 1, 'moderatedBy': 'RIA.com'}, 'state_id': 2},
>                  #csv_dataset_path=csv_dataset_path, # or None if you don`t have moderated data
>                  prisets={
>                      "eu": {
>                          "for_regions": ["eu"],
>                          "model_path": "latest"
>                      },
>                  },
>                  default_label = "eu",
>                  quality_profile=[5, 2, 0])
> ```
> 
> там грамматическая ошибка prisets (правильно presets), но пока что это не пофиксили, поэтому пишем "prisets"

всё четко вырезало подскажите куда дальше смотреть, а именно запускать для дообучения и модерирования процесса

**Comment by SergeKZ** [comment]
Еще столкнулся с такой ошибкой, думаю както надо указать юзать чисто СPU ?

`terminate called after throwing an instance of 'c10::HIPError'
  what():  HIP error: hipErrorNoDevice
Exception raised from deviceCount at /pytorch/aten/src/ATen/hip/impl/HIPGuardImplMasqueradingAsCUDA.h:102 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f4c7c482212 in /usr/local/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x5618da (0x7f4c2dbae8da in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_hip.so)
frame #2: torch::autograd::Engine::start_device_threads() + 0x21a (0x7f4c6413a3aa in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1134f (0x7f4c80c7f34f in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #4: torch::autograd::Engine::initialize_device_threads_pool() + 0xcd (0x7f4c6413919d in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x28 (0x7f4c64140058 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x3c (0x7f4c77313a3c in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #7: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x900 (0x7f4c6413e280 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #8: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x56 (0x7f4c77313996 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #9: THPEngine_run_backward(_object*, _object*, _object*) + 0x9d4 (0x7f4c773144a4 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>

Aborted (core dumped)`
