### ISSUE TITLE
Dataset for Detection + OCR pipeline and comparison with Nomeroff-Net

### ISSUE THREAD

**Issue by savchenkoyana** [ria-com/nomeroff-net#248]
Hello! Thank you for this amazing project!

At the moment I try to implement my own model for the license plate detection and recognition. I want to compare my model performance with Nomeroff-Net results. Do you have any dataset with non-cropped images annotated with bboxes and license plate numbers so that I can use it in my pipeline (detection + OCR)?

And also, in [your post](https://habr.com/ru/post/439330/) it is written that you reached ~ 97% word accuracy on Ukrainian numbers. Did you use the test part of [this dataset](https://nomeroff.net.ua/datasets/autoriaNumberplateOcrUa-2021-08-25.zip) for metrics evaluation? Is 97% accuracy only OCR metrics or you make detection + OCR and then compute metrics? If not, did you try to measure full pipeline (detection + OCR) metrics and what were your results?

Thanks,
Yana

**Comment by ApelSYN** [comment]
> At the moment I try to implement my own model for the license plate detection and recognition. I want to compare my model performance with Nomeroff-Net results. Do you have any dataset with non-cropped images annotated with bboxes and license plate numbers so that I can use it in my pipeline (detection + OCR)?

All datasets related to this project are made [publicly available](https://nomeroff.net.ua/datasets/). There are no datasets that you are interested in. 
For some types of numbers, we bought datasets on the site [platesmania](platesmania.com), we do not have the right to distribute them, they give xml with links to uncut photos. On these datasets, you can evaluate your and our algorithm.

> And also, in [your post](https://habr.com/ru/post/439330/) it is written that you reached ~ 97% word accuracy on Ukrainian numbers. Did you use the test part of [this dataset](https://nomeroff.net.ua/datasets/autoriaNumberplateOcrUa-2021-08-25.zip) for metrics evaluation? Is 97% accuracy only OCR metrics or you make detection + OCR and then compute metrics? If not, did you try to measure full pipeline (detection + OCR) metrics and what were your results?

The information in this article is already outdated, now the accuracy on Ukrainian OCR is higher (for cropped & normalized OCR model only). 

We have a small script for taking measurements of what you asked about. There are a small number of numberplates.
https://github.com/ria-com/nomeroff-net/blob/master/examples/ju/benchmark/accuracy-test.ipynb

**Comment by savchenkoyana** [comment]
@ApelSYN got it! Many thanks!
