### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by sashabal** [ria-com/nomeroff-net#25]
Hi
I am get Error, when try to run script "Hello Nomeroff Net":

Traceback (most recent call last):
  File "start.py", line 73, in <module>
    regionIds, isHiddenIds = optionsDetector.predict(zones)
ValueError: too many values to unpack (expected 2)

How to fix this error?

Same error:
~/nomeroff-net/examples/py$ python3 demo0.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "demo0.py", line 72, in <module>
    regionIds, stateIds = optionsDetector.predict(zones)
ValueError: too many values to unpack (expected 2)

**Comment by dimabendera** [comment]
Hello
In new versions we added one more parameter, that means count lines in number plate, so you may replace
```python
regionIds, isHiddenIds = optionsDetector.predict(zones)
```
on 
```python
regionIds, stateIds, countLines = optionsDetector.predict(zones)
```
See [https://github.com/ria-com/nomeroff-net/blob/master/examples/demo3.ipynb](https://github.com/ria-com/nomeroff-net/blob/master/examples/demo3.ipynb) and do not forget to use the latest models.
Thanks for letting us know about this problem, we will fix it soon.
