### ISSUE TITLE
ModuleNotFoundError: No module named 'modelhub_client'

### ISSUE THREAD

**Issue by abdalkaderhajjouz** [ria-com/nomeroff-net#252]
![image](https://user-images.githubusercontent.com/49202101/201478078-55d26052-bf50-44a4-bcad-212e89e84303.png)

How I can solve this please

thank you

**Comment by abdalkaderhajjouz** [comment]
![image](https://user-images.githubusercontent.com/49202101/203162969-cc87afb4-e12e-45a2-b344-4d4f18a89809.png)

**Comment by abdalkaderhajjouz** [comment]
uptill now I face same error

**Comment by dimabendera** [comment]
The problem is that you are running code in a virtual environment.
Try to do
```
source venv/bin/activate
```
and then install dependencies
```
pip3 install -r requirements.txt 
```

**Comment by ApelSYN** [comment]
This error means that you do not have the modelhub_client module installed, it can be installed with the command:
```bash
python3 -m pip install git+https://github.com/ria-com/modelhub-client.git
```

**Comment by Kostyashim** [comment]
Уже несколько раз устанавливал этот модуль разными способами

**Comment by Kostyashim** [comment]
![Uploading Снимок экрана 2024-07-02 в 09.12.24.png…]()

**Comment by Kostyashim** [comment]
<img width="1920" alt="Снимок экрана 2024-07-02 в 09 12 24" src="https://github.com/ria-com/nomeroff-net/assets/153326215/85a8694b-c871-41d9-bd5b-24952c75efd4">

**Comment by Kostyashim** [comment]
Как я понял возникают проблемы с областью видимости...
