### ISSUE TITLE
Error demo3.py

### ISSUE THREAD

**Issue by sashabal** [ria-com/nomeroff-net#27]
Hello

I am  have error, when I want running script demo3.py
Path: ~/examples/py/demo3.py

$ python demo3.py
File "demo3.py", line 78
cv_img_masks = await filters.cv_img_mask_async(NP)

I am using python v3.6
Can you help me with solve this problem?

**Comment by sashabal** [comment]
I understand correctly that the problem with async - library?
Is using async solver problem with the speed working system?

Thank you!

**Comment by dimabendera** [comment]
> I understand correctly that the problem with async - library?

Yes it is

> Is using async solver problem with the speed working system?

Yes, but not essential
