### ISSUE TITLE
Некорректное распознавание номеров в 3 строки

### ISSUE THREAD

**Issue by Liubov-Makohon** [ria-com/nomeroff-net#276]
Добрый день!

При распознавании номеров, состоящих из трех строк (например, номера мотоциклов), фреймворк не справляется с распознаванием и выдаёт неверные результаты. 

![изображение](https://github.com/ria-com/nomeroff-net/assets/82119866/66ea9add-a435-49c1-92d0-b6c0502ea12e)
Получаю номер BB9799EC

В Online Demo получаю следующий результат: 
![изображение](https://github.com/ria-com/nomeroff-net/assets/82119866/a275b392-dd9a-45c2-a368-2fbab2b0b2e3)

Версия Nomeroff Net: 3.4.1

**Comment by dimabendera** [comment]
![Screenshot from 2024-12-16 08-43-11](https://github.com/user-attachments/assets/02e4fc4c-2f03-4c50-8fc1-c0c16c6b5d66)
