### ISSUE TITLE
Error in nomeroff-net setup command: 'install_requires'

### ISSUE THREAD

**Issue by Yarwoll** [ria-com/nomeroff-net#281]
Error when git clonning repository:
 Running command git clone --filter=blob:none --quiet https://github.com/ria-com/nomeroff-net.git /tmp/pip-req-build-n245snbg
  Resolved https://github.com/ria-com/nomeroff-net.git to commit 743a86245da157bff9296958acfa85645b377a0e
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in nomeroff-net setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; .* suffix can only be used with `==` or `!=` operators
          imgaug>=0.4.*
                ~~~~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.


imgaug dependency is specified with an invalid version specifier. In Python package versioning, using a .* suffix is only valid with the == or != operators, not with >= or other operators.

**Comment by ApelSYN** [comment]
Find the problematic line in the "requirements.txt" file and remove the version:
"imgaug>=0.4.*" replace with "imgaug"
"torch>=1.12" replace with "torch"
and so on ...
