### ISSUE TITLE
Уменьшение времени распознования.

### ISSUE THREAD

**Issue by danilpan** [ria-com/nomeroff-net#29]
Добрый день! 
Запустили проект на Tensorflow GPU, но время распознования сократилось только до 5 секунд. Хотелось бы сократить время до 1-2 секунд. 
Комп: i7 8800k, GTX 1080 8G
Заранее спасибо за помощь.

**Comment by ApelSYN** [comment]
Комп нормальный, должно быть в районе 1c, может что-то не так поставилось, похоже что Вас прессинг идет на CPU, возможно забыли поправить в примере переменную 
```python
mode = "gpu"
```

Напишите нам вывод запуска вот этого кода, чтоб понимать что у Вас все нормально с tf gpu:
```python
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
c = tf.matmul(a, b)
print(sess.run(c))
```

**Comment by danilpan** [comment]
*Спасибо за ответ. Вот вывод после запуска Вашего кода:*
WARNING: Logging before flag parsing goes to stderr.
W0717 18:20:31.254466 139731632719680 module_wrapper.py:126] From
/home/server/.envs/tensorflow/lib/python3.6/site-packages/tensorflow_core/python/util/module_wrapper.py:153:
The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-07-17 18:20:31.256368: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcuda.so.1
2019-07-17 18:20:31.275221: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.275765: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with
properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:01:00.0
2019-07-17 18:20:31.275935: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcudart.so.10.0
2019-07-17 18:20:31.276757: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcublas.so.10.0
2019-07-17 18:20:31.277587: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcufft.so.10.0
2019-07-17 18:20:31.277756: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcurand.so.10.0
2019-07-17 18:20:31.279493: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcusolver.so.10.0
2019-07-17 18:20:31.280220: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcusparse.so.10.0
2019-07-17 18:20:31.282311: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcudnn.so.7
2019-07-17 18:20:31.282387: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.282904: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.283274: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu
devices: 0
2019-07-17 18:20:31.283297: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library libcudart.so.10.0
2019-07-17 18:20:31.351876: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect
StreamExecutor with strength 1 edge matrix:
2019-07-17 18:20:31.351910: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-07-17 18:20:31.351915: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-07-17 18:20:31.352104: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.352470: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.352790: I
tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
2019-07-17 18:20:31.353220: I
tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow
device (/job:localhost/replica:0/task:0/device:GPU:0 with 6856 MB memory)
-> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id:
0000:01:00.0, compute capability: 6.1)
Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce
GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1
2019-07-17 18:20:31.354040: I
tensorflow/core/common_runtime/direct_session.cc:356] Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce
GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1

MatMul: (MatMul): /job:localhost/replica:0/task:0/device:GPU:0
2019-07-17 18:20:31.356179: I tensorflow/core/common_runtime/placer.cc:54]
MatMul: (MatMul)/job:localhost/replica:0/task:0/device:GPU:0
a: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2019-07-17 18:20:31.356192: I tensorflow/core/common_runtime/placer.cc:54]
a: (Const)/job:localhost/replica:0/task:0/device:GPU:0
b: (Const): /job:localhost/replica:0/task:0/device:GPU:0
2019-07-17 18:20:31.356197: I tensorflow/core/common_runtime/placer.cc:54]
b: (Const)/job:localhost/replica:0/task:0/device:GPU:0
[[22. 28.]
 [49. 64.]]


ср, 17 июл. 2019 г. в 18:17, Oleg Cherniy <notifications@github.com>:

**Comment by ApelSYN** [comment]
С поддержкой GPU у Вас все нормально, мне кажется, я не совсем правильно понял Ваш вопрос.
Для того чтоб померять быстродействие нужно запустить вот этот скрипт [runtime.ipynb](https://github.com/ria-com/nomeroff-net/blob/master/banchmarks/runtime.ipynb)

Если Вы запускаете пример "Hello World", то там быстродействие расходуется, в основном, на загрузку моделей и таким образом пользоваться нашей библиотекой неоптимально.

План решения проблемы следующий: пишем Web-приложение (например, мы используем [tornado](https://www.tornadoweb.org/en/stable/)), грузим модели, и даем доступ к инфернсу модели через REST. Тогда можно получить быстродействие порядка ~1s/фото. Мы это уже обсуждали [в этой ветке](https://github.com/ria-com/nomeroff-net/issues/19)

**Comment by danilpan** [comment]
Прочитав советы в той ветке, из написанного вывели что при каждом новом запуске скрипта у нас происходит новая загрузка моделей. Не могли бы подсказать как загрузить модельки только единожды? а ваше решение через REST сервис я не совсем понимаю как поможет

**Comment by ApelSYN** [comment]
> Прочитав советы в той ветке, из написанного вывели что при каждом новом запуске скрипта у нас происходит новая загрузка моделей. Не могли бы подсказать как загрузить модельки только единожды? а ваше решение через REST сервис я не совсем понимаю как поможет

Нужно сделать так чтоб скрипт запустился, загрузил модели и не приостанавливал свою работу. Такой скрипт можно оформить в виде сервиса (не обязательно REST-сервиса), также можно "общаться" со скриптом через сервис очередей, например RabbitMQ.

Чтоб вам было понятнее в режиме сервиса на вашем компьютере  работает  база данных, веб-сервер, memcache и т.д. Они не запускаются каждый раз когда вы к ним обращаетесь -- они стартуют и останавливается, как правило, вместе со стартом и остановкой компьютера.

**Comment by danilpan** [comment]
Оказывается мы каждый раз при новой фотографии делали выгрузку модели, решили мы этому проблему с переносом этой части кода в начало запуска нашего софта и теперь время обработки у нас выходит ~0,5-1 сек
