### ISSUE TITLE
Підтримка yolo11 та segmentation model

### ISSUE THREAD

**Issue by KVInventoR** [ria-com/nomeroff-net#295]
Чи плануєте додати yolo11 з segmentation model?
Трохи погрався з цим і виглядає реально чудово, на багато простіше знайти область з номером на зображені, та потім відправити на розпізнавання

**Comment by ApelSYN** [comment]
> Чи плануєте додати yolo11 з segmentation model? Трохи погрався з цим і виглядає реально чудово, на багато простіше знайти область з номером на зображені, та потім відправити на розпізнавання

Ні не плануємо. Ми це вже давно проходили, коли використовували Mask RCNN. На виході ви одержуєте бінарну маску її ще потрібно потім обробити щоб одержати правильні 4 кута номера. Це доволі затратно по ресурсам і результат буде досить посереднім якщо мова йде про багатолінійні номери.
