### ISSUE TITLE
Mask RCNN epochs

### ISSUE THREAD

**Issue by Spectra456** [ria-com/nomeroff-net#41]
Добрый день! Сколько эпох использовали для тренировки?

**Comment by dimabendera** [comment]
<a href="https://nomeroff.net.ua/models/mrcnn/mask_rcnn_numberplate_0640_2019_06_24.h5">Последняя модель </a> была натренированна на 640 эпохах.
Но после 100 эпохи функция ошибки не сильно изменяется.
