### ISSUE TITLE
Resource exhausted

### ISSUE THREAD

**Issue by Elephmoon** [ria-com/nomeroff-net#42]
Добрый день. Скопировал ваш проект, пытаюсь обучать на вашем датасете.
ошибка показана на скрине ниже.
проблема начинается в процессе обучения, на первоё 
эпохе. Интересует это недостаточно производительности у GPU? или можно как то дотюнить модель, чтобы она влезла на GPU?
GPU nvidia gtx 970 4 Гб памяти.
![11](https://user-images.githubusercontent.com/16652418/64920203-4b157900-d7bd-11e9-9de2-983ebcf43681.png)
![22](https://user-images.githubusercontent.com/16652418/64920206-510b5a00-d7bd-11e9-97d9-78007f8772aa.png)

**Comment by Elephmoon** [comment]
и если не секрет, то на каком gpu обучалось?

**Comment by ApelSYN** [comment]
> Добрый день. Скопировал ваш проект, пытаюсь обучать на вашем датасете.
ошибка показана на скрине ниже.
Это ошибка в датасете, неверное описание региона, проблема с файлом 250022241orig.jpeg, можете самостоятельно пофиксить скорее всего там одна из координат больше чем размер фото, в ошибке есть подсказка что не нравиться. Завтра на работе смогу пофиксить и выложить обновленный json с описанием.
> и если не секрет, то на каком gpu обучалось?
Мы тренируем на GeForce GTX 1080 TI или GeForce RTX 2080 TI

**Comment by Elephmoon** [comment]
Спасибо

**Comment by Elephmoon** [comment]
датасет исправил, но наверное проблема всё таки в видюхе. thread exception полетели, и Resource exhausted. можно какие то параметры подправить кроме IMAGES_PER_GPU для увеличения производительности?
![33](https://user-images.githubusercontent.com/16652418/64936551-37225380-d85f-11e9-977b-8df8a75dba48.png)
![44](https://user-images.githubusercontent.com/16652418/64936552-3a1d4400-d85f-11e9-802c-04f5ab98efdb.png)

**Comment by dimabendera** [comment]
Рекомендую вам посмотреть сюда https://github.com/matterport/Mask_RCNN/blob/master/mrcnn/config.py


Все те же параметры можно  передать в конструктор nomeroffNet.Detector
Например:
```python
detector = Detector(mask_rcnn_dir="./MaskRCNN/", log_dir="./logs/", mask_rcnn_config={
          "NAME": "numberplate",
          "GPU_COUNT": 1,
          "IMAGES_PER_GPU": 1,
          "NUM_CLASSES": 2,
          "DETECTION_MIN_CONFIDENCE": 0.7,
          "IMAGE_MAX_DIM": 1024, # work ?
          "IMAGE_RESIZE_MODE": "square" # work ?
        })
```

**Comment by Elephmoon** [comment]
Обучение стартануло с вот такими параметрами. GPU nvidia 970
![2222](https://user-images.githubusercontent.com/16652418/65322261-fef87900-dbae-11e9-9336-fa2c7001b17f.png)
