### ISSUE TITLE
Ошибка list index out of range при вызове convert_keras_to_freeze_pb

### ISSUE THREAD

**Issue by ramil8090** [ria-com/nomeroff-net#43]
Добрый день,
пытаюсь выполнить скрипт ocr-ru.ipynb, но получаю ошибку IndexError: list index out of range. Подскажите, пожалуйста, в чем проблема. Заранее благодарен. Прилагаю скрипт с ошибкой.

Python 3.7
tensorflow (14) пробовал и 13ю версию.
GPU нет, запускаю на ноутбуке.

[ocr-ru.ipynb.zip](https://github.com/ria-com/nomeroff-net/files/3653815/ocr-ru.ipynb.zip)

**Comment by dimabendera** [comment]
Здраствуйте, дело в вашей версии keras. <a href="https://github.com/keras-team/keras#multi-backend-keras-and-tfkeras">C версии Keras 2.3.0 он использует как бэкенд tensorflow 2</a>. Из за этого и возникают проблемы. Пожалйста выполните команду:
```
pip3 install keras=2.2.4
```

**Comment by ramil8090** [comment]
Огромное спасибо, Дмитрий! Вы были совершенно правы, дело в версии Keras. Установка версии 2.2.4 помогла.
