### ISSUE TITLE
demo3.ipynb using await causes SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by VesninEN** [ria-com/nomeroff-net#5]
When I running demo3.ipynb I got this error
  File "<ipython-input-18-756c7305cdce>", line 29
    cv_img_masks = await filters.cv_img_mask_async(NP)
                               ^
SyntaxError: invalid syntax

**Comment by dimabendera** [comment]
What versions of Python and Jupyther are you using?
Run in docker?

**Comment by ApelSYN** [comment]
Python <3.5 does not support async / await
