### ISSUE TITLE
Не работает админка

### ISSUE THREAD

**Issue by kekonaut** [ria-com/nomeroff-net#51]
После обработки всех фотографий не загружаются json файлы

**Comment by ApelSYN** [comment]
Уточните о каком скрипте идет речь, какая ошибка возникает?

**Comment by kekonaut** [comment]
Об админке для разметки фотографий. После разметки всех фотографийй, json файлы не сохраняются в папке ann

**Comment by ApelSYN** [comment]
Уточняю вопросы:

1) Какая ошибка возникает в консоли там где вы запустили?
node ./server.js 

2) Имеет ли пользователь от которого запущен скрипт в консоли права на запись в папку где происходит разметка данных (в вашем случае папку "ann")?

**Comment by kekonaut** [comment]
1) Никакая. Последние записи GET /img/<name>
есть еще {
  img_path: <name>,
  name: <name>,
  predicted: '',
  description: undefined
}

2)да, имеет

**Comment by ApelSYN** [comment]
Должно быть как-то так:
```javascript
{
  img_path: 'img/238144554.png',
  name: '238144554',
  predicted: '',
  description: undefined
}
{
  img_path: 'img/256425853.png',
  name: '256425853',
  predicted: '',
  description: undefined
}
```
Формат фото png? Если нет, то сконвертируйте в png и попробуйте еще раз.

Если проблема еще осталась вышлите мне конфиг и несколько фото из вашего датасета, напишите в какой папке эти фото лежат.

**Comment by kekonaut** [comment]
Помогла смена формата с .jpg на .png 
Спасибо!
