### ISSUE TITLE
Ошибка во время обучения собственной ocr

### ISSUE THREAD

**Issue by kekonaut** [ria-com/nomeroff-net#52]
Для обучения ocr пользуюсь файлом ocr.py из папки train/py/
возникает ошибка keyError
GET ALPHABET
Max plate length in "val": 9
Traceback (most recent call last):
  File "/nomeroff-net-master/train/py/ocr.py", line 31, in <module>
    model = ocrTextDetector.prepare(PATH_TO_DATASET, aug_count=0)
  File "/nomeroff-net-master/NomeroffNet/Base/OCR.py", line 221, in prepare
    self.letters, max_plate_length = self.get_alphabet(train_path, test_path, val_path, verbose=verbose)
  File "/nomeroff-net-master/NomeroffNet/Base/OCR.py", line 81, in get_alphabet
    c_train, max_plate_length_train = self.get_counter(train_path)
  File "/nomeroff-net-master/NomeroffNet/Base/OCR.py", line 71, in get_counter
    description = json.load(open(json_filepath, 'r'))['description']
KeyError: 'description'

**Comment by ApelSYN** [comment]
У Вас проблемы с датасетом, на основе которого вы пытаетесь произвести обучение. Проверте наличие поля 'description' в .json-фойлах с описанием в папке "ann" вашего датасета.

**Comment by kekonaut** [comment]
поле description присутствует вместе с ключом в json файлах. Однако поле 'predictions':""

**Comment by ApelSYN** [comment]
> description = json.load(open(json_filepath, 'r'))['description']
> KeyError: 'description'
Все равно перепроверте, это уведомление говорит о том что с 'description' какая-то проблема.
'predictions' впромагательное поле, при обучении оно не используется. И еще, 'description' не может быть пустым, примеры где нет номеров нету смысла включать в обучение.

**Comment by ApelSYN** [comment]
Я поясню на примере:
Берем номер:
![UA simple numberplate](https://nomeroff.net.ua/images/github/0HlrAOMhf1gu5TWz4SUcQ3ZnJXL9BG6jbtexpDaId2VEmiRKwq.png)

Определяем возможные зоны с текстом:

составляем хитмап (Heatmap) "потенциальных" участков с текстом
![UA simple numberplate](https://nomeroff.net.ua/images/github/numberplate_heatmap.png)

формируем потенциальные границы зон с текстом
![UA simple numberplate](https://nomeroff.net.ua/images/github/potential_text_lines.png)

отбрасываем ненужные зоны
![UA simple numberplate](https://nomeroff.net.ua/images/github/terget_text_lines.png)

Теперь можно склеить все в одну строку 
![UA simple numberplate](https://nomeroff.net.ua/images/github/terget_numberplate_line.png)

Инструмент которым мы пользуемся для детекции текстовых зон называется [CRAFT](https://github.com/clovaai/CRAFT-pytorch). Это не очень оптимальный способ решения поставленой задачи, CRAFT достаточно "тяжелый" фреймворк, возможно в будущем нам прийдется использовать что-то "полегче". Когда у нас будет более-мение стабильное и универсальное решение, которое можно применить к любым типам квадратных номеров мы его выложим в открытый доступ.
