### ISSUE TITLE
ошибка tensorflow

### ISSUE THREAD

**Issue by flash1nho** [ria-com/nomeroff-net#53]
И снова привет :)
подскажите пожалуйста, в чем я не прав?))) tensorflow = 1.15 или tensorflow = 2.0

No module named 'tensorflow_core.keras'

**Comment by dimabendera** [comment]
Nomeroff-Net использует под собой tensorflow 1.5

**Comment by flash1nho** [comment]
извиняюсь, ставил 1.5, не 1.15

**Comment by dimabendera** [comment]
Извиняюсь, 1.15

**Comment by flash1nho** [comment]
не знаю, как решить

**Comment by flash1nho** [comment]
return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.keras'

**Comment by flash1nho** [comment]
Поддержка GPU есть, python3.6.1

**Comment by dimabendera** [comment]
Попробуйте запустить
pip3 uninstall tensorflow_estimator
pip3 install tensorflow_estimator

Если это не поможет запустите
python3
from tensorflow.python.client import device_lib
local_device_protos = device_lib.list_local_devices()
print([x.name for x in local_device_protos if x.device_type])

Это должно вывести все доступные TensorFlow девайсы

**Comment by flash1nho** [comment]
['/device:CPU:0', '/device:XLA_CPU:0', '/device:XLA_GPU:0', '/device:GPU:0']

**Comment by dimabendera** [comment]
Тогда проверьте ещё какая версия keras у вас стоит
python3 -c "import keras; print(keras.__version__)"

**Comment by flash1nho** [comment]
2.3.1

**Comment by dimabendera** [comment]
Дело в версии keras. С версии 2.3.0 он поддерживает дефолтно tensorflow 2.0
Подробнее тут
https://github.com/keras-team/keras#multi-backend-keras-and-tfkeras
Что бы исправить это запустите
pip3 install keras==2.2.5

**Comment by flash1nho** [comment]
пока не помогло, ладно, спасибо

**Comment by dimabendera** [comment]
Так же возможно что проблемы возникают с неправильно установленными CUDA/CUDNN
Какую оперативную систему вы используете?

**Comment by flash1nho** [comment]
ubuntu 18

**Comment by dimabendera** [comment]
Запустите
`nvcc --version`
или
`nvidia-smi`
Что бы проверить версию установленной CUDA

**Comment by flash1nho** [comment]
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:03:00.0 Off |                  N/A |
| 20%   50C    P0    62W / 250W |      1MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by flash1nho** [comment]
У меня все работает по майской вашей версии.

**Comment by flash1nho** [comment]
Вы помогали мне решить проблему по этой задаче. https://github.com/ria-com/nomeroff-net/issues/19

**Comment by flash1nho** [comment]
Решилось.
Установил tensorflow 1.6.0-rc0
Установил Keras 2.2.5

Заменил https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/Base/TextImageGenerator.py#L6 на from tensorflow.python.keras import backend as K
Заменил https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/Base/OCR.py#L2 на import tensorflow.python.keras

Полетели.

**Comment by flash1nho** [comment]
ерунду написал) ничего не верно и не работает

**Comment by dimabendera** [comment]
У вас вылетает программа на этой строке?
from tensorflow.python.keras import backend as K

Попробуйте запустить её с консоли
python3 -c "from tensorflow.python.keras import backend as K"

Возникает та же ошибка?

**Comment by flash1nho** [comment]
Здравствуйте! Пока задачу прикрою, по ходу проблема была во flask, но если будут проблемы дальше, обращусь) Спасибо за помощь!

**Comment by flash1nho** [comment]
И вот поймал ошибку:
строка
```
NP = nnet.detect([img])
```

```
raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("mrcnn_detection/Reshape_1:0", shape=(1, 100, 6), dtype=float32) is not an element of this graph.
```

**Comment by GalymzhanAbdimanap** [comment]
У меня была такая ошибка когда я обрабатывал асинхронно. Я решил это так: 
Берете в основном потоке граф "graph = tf.get_default_graph()"  и на другом потоке используете этот граф with graph.as_default():
                       NP = nnet.detect([img_np])




"graph = tf.get_default_graph()
with graph.as_default():
    NP = nnet.detect([img_np])"

**Comment by flash1nho** [comment]
Спасибо, помогло следующее https://github.com/matterport/Mask_RCNN/issues/588#issuecomment-425219274

**Comment by flash1nho** [comment]
теперь другая ошибка)))
ValueError: Tensor Tensor("softmax_ru/truediv:0", shape=(?, 32, 23), dtype=float32) is not an element of this graph.
