### ISSUE TITLE
об OCR

### ISSUE THREAD

**Issue by GalymzhanAbdimanap** [ria-com/nomeroff-net#55]
Добрый день. Это личный вопрос из интереса. Хотел узнать как  OCR  распознавание распознает символы? как он определяет в каком месте картинки какой символ? Как во время обучения обучается OCR разпознавалка? Как она определяет символы на картинке? Был бы очень рад, если вы расскажете по подробнее. Я хотел бы попробовать обучить вашу OCR  модель на датасете рукописных текстов. Первый результат дал 75% точности на тестовых данных, но это пока не удовлетворительно. Благодарю за ответ.

**Comment by dimabendera** [comment]
Мы не изобретали свою OCR модель, а взяли "готовую".
Чтобы понять как работает модель ознакомьтесь с оригинальными статьями:
[Часть 1](https://towardsdatascience.com/number-plate-detection-with-supervisely-and-tensorflow-part-1-e84c74d4382c)
[Часть 2](https://hackernoon.com/latest-deep-learning-ocr-with-keras-and-supervisely-in-15-minutes-34aecd630ed8)

А также настоятельно рекомендую ознакомится с [этой презентацией](https://docs.google.com/presentation/d/12gYcPft9_4cxk2AD6Z6ZlJNa3wvZCW1ms31nhq51vMk/pub?start=false&loop=false&delayms=3000&slide=id.g24e9f0de4f_0_332).

**Comment by GalymzhanAbdimanap** [comment]
Спасибо за ответ
