### ISSUE TITLE
Использование OCR

### ISSUE THREAD

**Issue by kekonaut** [ria-com/nomeroff-net#58]
Добрый день! Хотелось бы проверить ocr на отдельной картинке с номером, однако, она не распознает номер, если вставлять картинку в демо пример. Не очень понимаю, как ее использовать отдельно от модели детектирования машин
Не могли бы вы , пожалуйста, описать алгоритм использования отдельно ocr

**Comment by ApelSYN** [comment]
Не совсем понятен ваш вопрос.

**Comment by kekonaut** [comment]
Хочу проверить работу обученных ocr на фотографиях, которые содержат только номер( обрезанные)
Понимаю,что это возможно сделать, но можно ли как-то вытащить из демо только работу ocr на фотографиях, без детектирования объектов на ней. Т.к. насколько я понимаю, сначала в демо детектируются объекты : машины, номера. А потом только применяется ocr
спасибо!

**Comment by ApelSYN** [comment]
Возмите скрипт для тренировки и положите примеры с описанием в папку test. Вместо тренировки загрузите модель 
```python
model = ocrTextDetector.load("/var/www/nomeroff-net/NomeroffNet/mcm/models/TextDetector/ru/anpr_ocr_ru_3-cpu.h5")
```
Потом запустите 
```python
ocrTextDetector.test(verbose=True)
```
Там вам покажет что распознается неправильно.

**Comment by kekonaut** [comment]
Спасибо большое за ответ!
Да, но тогда у меня выдается та же ошибка, что и при обучении через ipynb 
AttributeError: 'ru' object has no attribute 'tiger_test'
Вероятно, у меня что-то не так импортируется. Думала изначально, что это ошибка присущая именно этому формату

**Comment by GalymzhanAbdimanap** [comment]
Попробуйте так
from NomeroffNet import  TextDetector
import matplotlib.pyplot as plt


# Initialize text detector.
textDetector = TextDetector.get_static_module("ru")()
textDetector.load("latest")

zones=plt.imread('number_plate.jpg')

textArr = textDetector.predict([zones])
#textArr = textPostprocessing(textArr)
print(textArr)

**Comment by kekonaut** [comment]
Спасибо!

**Comment by kekonaut** [comment]
А возможно ли вырезать номера из картинок, где присутствует только номер на каком-либо фоне, а не машина целиком?
Пыталась использовать такие фото для модели. Она не распознает на них номера

**Comment by GalymzhanAbdimanap** [comment]
Сделайте так
import os
import numpy as np
import sys
import matplotlib.image as mpimg
import cv2
import glob
from datetime import datetime
#change this property
NOMEROFF_NET_DIR = os.path.abspath('../../')

#specify the path to Mask_RCNN if you placed it outside Nomeroff-net project
MASK_RCNN_DIR = os.path.join(NOMEROFF_NET_DIR, 'Mask_RCNN')
MASK_RCNN_LOG_DIR = os.path.join(NOMEROFF_NET_DIR, 'logs')

#sys.path.append(NOMEROFF_NET_DIR)

#Import license plate recognition tools.
from NomeroffNet import  filters, RectDetector, TextDetector, OptionsDetector, Detector, textPostprocessing, textPostprocessingAsync
#from OptionsDetector import OptionsDetector

#Initialize npdetector with default configuration file.
nnet = Detector(MASK_RCNN_DIR, MASK_RCNN_LOG_DIR)
nnet.loadModel("latest")

rectDetector = RectDetector()

optionsDetector = OptionsDetector()
optionsDetector.load("latest")

#Initialize text detector.
textDetector = TextDetector.get_static_module("kz")()
textDetector.load("latest")


#Detect numberplate
images = glob.glob('images500/*.jpg')


def boxNumber2number(img):
    h,w = img.shape[:2]
    crop_img1 = img[0:int(h/1.8), 0:int(w)]
    crop_img2 = img[int(h/1.8):int(h), 0:int(w)]
    img1=cv2.resize(crop_img1,(int(w),60))
    img2=cv2.resize(crop_img2,(int(w),60))
    vis = np.concatenate((img1, img2), axis=1)
    return [vis]

#приводим в формат квадратные номера
def box_plate(number):
    if len(number)==8 and number[:1] in '1234567890':
        part1=number[:3]
        part2=number[-3:]
        part3=number[3:-3]
        number = str(part1)+str(part2)+str(part3)
    elif len(number)==7 and number[:1] in '1234567890':
        part1=number[:3]
        part2=number[-2:]
        part3=number[3:-2]
        number = str(part1)+str(part2)+str(part3)
    else:
        number=number
    return number


for img_path in images:
    img = cv2.imread(img_path)
    #img = [img]

    NP = nnet.detect([img])

    #Generate image mask.
    cv_img_masks = filters.cv_img_mask(NP)

   
    photo_time = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")
    arrPoints = rectDetector.detect(cv_img_masks)
    zones = rectDetector.get_cv_zonesBGR(img, arrPoints)
    regionIds, stateIds, countLines = optionsDetector.predict(zones)
    if len(countLines)>0:
        if countLines[0]==2:
            zones = boxNumber2number(zones[0])
    regionNames = optionsDetector.getRegionLabels(regionIds)
    #print("CL: "+str(countLines))
    textArr = textDetector.predict(zones, countLines)
    textArr = textPostprocessing(textArr, regionNames)
    if len(countLines)>0:
        if countLines[0]==2:
            textArr[0] = box_plate(textArr[0])
    #print(textArr)
    print(img_path)
    if len(zones)>0:
        cv2.imwrite("number_plates/car"+str(photo_time)+'-'+str(textArr[0]+'.jpg'), zones[0]) 
    else:
        continue

**Comment by GalymzhanAbdimanap** [comment]
Если не ошибаюсь номер должен составлять не более 10% изображения, проверьте сколько процентов от изображения составляет номер.

**Comment by ApelSYN** [comment]
> А возможно ли вырезать номера из картинок, где присутствует только номер на каком-либо фоне, а не машина целиком?
> Пыталась использовать такие фото для модели. Она не распознает на них номера

Мы натренировали Mask RCNN модель под нужды сайта AUTO.RIA.com, наши пользователи не фотографируют крупным планом номер, а, обычно, автомобиль на котором (в том числе) видно номер, поэтому наилучшый выход из ситуации, натренировать свою модель.

Вы можете внимательно изучить мои статьи на хабре и вот этот [скрипт](https://github.com/ria-com/nomeroff-net/blob/master/train/mrcnn.ipynb), с помощью которого можно создать свою модель, которая сможет искать по вашему датасету.

Для этого нужно разметить хотя бы 300 фото (а лучше около 1000) из вашего датасета, можете дотренировать нашу модель с этими данными или дотренировать coco-датасет (в конфиг в параметр  "WEIGHTS" пишем значение "coco"), после этого подключите созданую вами модель и все будет находить.

**Comment by GalymzhanAbdimanap** [comment]
Доброе утро, вопрос такой, я заметил в коде функцию aug.py,  но это не используется в обучении. Наверное это из за того что у вас и так было много картинок. Когда лучше всего использовать аугментацию? и как увеличиваются данные касательно aug_count? если я поставлю aug_count = 1, то это значить что данные увеличатся в двое? Спасибо
