### ISSUE TITLE
Чисто научный вопрос)

### ISSUE THREAD

**Issue by flash1nho** [ria-com/nomeroff-net#61]
Есть изображение: 
![изображение](https://user-images.githubusercontent.com/4254272/70112694-f70d8880-1677-11ea-9b52-776b595dc2eb.png)

Я уменьшаю его в два раза и начинаю детектить номер. Получаю следующее: ["T22T15"] - то есть неверно.

На вашем же ресурсе работает все ок.
![изображение](https://user-images.githubusercontent.com/4254272/70112752-36d47000-1678-11ea-9ff3-4d7449417e56.png)

Может есть идеи как распознавать уменьшенную копию изображения и превращать ее в оригинал ?:)

**Comment by GalymzhanAbdimanap** [comment]
Добрый день, в Detector.py  в конфигурациях  есть строка "IMAGE_MAX_DIM": 1024. Это качество фото, которое принимает нейронка, можете по тестировать уменьшив ее.

**Comment by flash1nho** [comment]
> Добрый день, в Detector.py в конфигурациях есть строка "IMAGE_MAX_DIM": 1024. Это качество фото, которое принимает нейронка, можете по тестировать уменьшив ее.

Спасибо, протестирую

**Comment by ApelSYN** [comment]
Мы используем те же модели, которые выложены открытый доступ на сайте. Возможно у вас неправильно происходит классификация номера и определяется что он не "ru", вы не перетренировывали Options под свои нужды?

**Comment by flash1nho** [comment]
> Мы используем те же модели, которые выложены открытый доступ на сайте. Возможно у вас неправильно происходит классификация номера и определяется что он не "ru", вы не перетренировывали Options под свои нужды?

Какой dataset лучше взять, чтобы натренировать по текущему коду?
```
import os
import sys
import warnings
warnings.filterwarnings('ignore')

# change this property
NOMEROFF_NET_DIR = os.path.abspath('../../')

DATASET_NAME = "options"
VERSION = "2019_11_25"

LOG_DIR = os.path.join(NOMEROFF_NET_DIR, "logs/")
PATH_TO_DATASET = os.path.join(NOMEROFF_NET_DIR, "datasets/", DATASET_NAME)
RESULT_PATH = os.path.join(NOMEROFF_NET_DIR, "models/", 'numberplate_{}_{}.h5'.format(DATASET_NAME, VERSION))

FROZEN_MODEL_PATH = os.path.join(NOMEROFF_NET_DIR, "models/", 'numberplate_{}_{}.pb'.format(DATASET_NAME, VERSION))

sys.path.append(NOMEROFF_NET_DIR)

from NomeroffNet import OptionsDetector
from NomeroffNet.Base import convert_keras_to_freeze_pb

class MyNumberClassificator(OptionsDetector):
    def __init__(self):
        OptionsDetector.__init__(self)
        # outputs 1
        self.CLASS_STATE = ["BACKGROUND", "FILLED", "NOT_FILLED"]

        # outputs 2
        self.CLASS_REGION = ["ru"]

        self.EPOCHS           = 2
        self.BATCH_SIZE       = 10

        self.HEIGHT         = 64
        self.WEIGHT         = 295

# initialize region detector.
numberClassificator = MyNumberClassificator()
numberClassificator.prepare(PATH_TO_DATASET)

# train
model = numberClassificator.train(LOG_DIR, cnn="simple")

numberClassificator.test()

numberClassificator.save(RESULT_PATH)
```

**Comment by flash1nho** [comment]
запустил скрипт в options для картинок
```
for file in `ls *.jpeg`; do
   Orientation=`exiftool -Orientation -n ${file} | awk '{print $3}'`;
   if [[ $Orientation -gt 1 ]]
   then
       echo "Fixing '${file}' - $Orientation "
       exiftool -Orientation=1 -n ${file}
   fi
done
```

**Comment by flash1nho** [comment]
Скачал датасет https://nomeroff.net.ua/datasets/autoriaNumberplateOptions3Dataset-2019-10-04.zip
поправил скриптом (https://github.com/ria-com/nomeroff-net/issues/61#issuecomment-561963653), ничего не выявилось.

Получаю ошибку
Ошибка IndexError: index 6 is out of bounds for axis 1 with size 2

Код options.py

```
import os
import sys
import warnings
warnings.filterwarnings('ignore')

# change this property
NOMEROFF_NET_DIR = os.path.abspath('../../')

DATASET_NAME = "options"
VERSION = "2019_11_25"

LOG_DIR = os.path.join(NOMEROFF_NET_DIR, "logs/")
PATH_TO_DATASET = os.path.join(NOMEROFF_NET_DIR, "datasets/", DATASET_NAME)
RESULT_PATH = os.path.join(NOMEROFF_NET_DIR, "models/", 'numberplate_{}_{}.h5'.format(DATASET_NAME, VERSION))

FROZEN_MODEL_PATH = os.path.join(NOMEROFF_NET_DIR, "models/", 'numberplate_{}_{}.pb'.format(DATASET_NAME, VERSION))

sys.path.append(NOMEROFF_NET_DIR)

from NomeroffNet import OptionsDetector
from NomeroffNet.Base import convert_keras_to_freeze_pb

class MyNumberClassificator(OptionsDetector):
    def __init__(self):
        OptionsDetector.__init__(self)
        # outputs 1
        self.CLASS_STATE = ["BACKGROUND", "FILLED", "NOT_FILLED"]

        # outputs 2
        self.CLASS_REGION = ["xx-unknown", "ru"]

        self.EPOCHS           = 2
        self.BATCH_SIZE       = 10

        self.HEIGHT         = 64
        self.WEIGHT         = 295

# initialize region detector.
numberClassificator = MyNumberClassificator()
numberClassificator.prepare(PATH_TO_DATASET)

# train
model = numberClassificator.train(LOG_DIR, cnn="simple")

numberClassificator.test()

numberClassificator.save(RESULT_PATH)
#model = numberClassificator.load(RESULT_PATH)

import keras
keras.backend.clear_session()
model = numberClassificator.load(RESULT_PATH)
convert_keras_to_freeze_pb(numberClassificator.MODEL, FROZEN_MODEL_PATH)
```

**Comment by ApelSYN** [comment]
Вы не поняли как это работает. Датасет прийдется пофиксить. 
1. В вашем датасете не должно быть картинок не с "ru" номерами. 
2. Индекс "ru" номеров уже будет иметь индекс 1, так как вы все другое удалили, в нашем примере у него индекс другой. Это надо самостоятельно пофиксить в json-файлах.

**Comment by flash1nho** [comment]
Спасибо! Все погрохал, индексы поменял, натренировал!

**Comment by flash1nho** [comment]
Явно указывал в options.py self.CLASS_REGION = ["xx-unknown", "ru"]

Почему-то у меня на этой картинке определяется другой регион - "eu-ua-2015"

сама картинка: 
![img](https://user-images.githubusercontent.com/4254272/70315386-48b24080-183b-11ea-8a52-b824b4b8debd.jpg)

**Comment by flash1nho** [comment]
Ваша демка детектит ['ru']

**Comment by ApelSYN** [comment]
Фиксить список надо не только в обучающей выборке но и в коде распознавания [NomeroffNet/OptionsDetector.py](https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/OptionsDetector.py)

**Comment by flash1nho** [comment]
> Фиксить список надо не только в обучающей выборке но и в коде распознавания [NomeroffNet/OptionsDetector.py](https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/OptionsDetector.py)

Оставил нужные регионы, натренировал. Теперь вообще не определяет  "eu-ua-2015", "xx-unknown", "ru". Возвращает пустой массив...

**Comment by ApelSYN** [comment]
Модель "Options" возвращает не один а несколько масивов значений, которые классифицирет модель после детекции зон.
Возьмем этот пример [examples/demo3.ipynb](https://github.com/ria-com/nomeroff-net/blob/master/examples/demo3.ipynb), вот в этой части:
> regionIds, stateIds, countLines = optionsDetector.predict(zones)

Если на входе есть зоны, то на выходе будет столько же елементов в списках 
regionIds, stateIds, countLines

Если зоны есть а списки пустые, значит вы что-то сделали неправильно, ищите ошибку.

**Comment by flash1nho** [comment]
> Модель "Options" возвращает не один а несколько масивов значений, которые классифицирет модель после детекции зон.
> Возьмем этот пример [examples/demo3.ipynb](https://github.com/ria-com/nomeroff-net/blob/master/examples/demo3.ipynb), вот в этой части:
> 
> ```python
> regionIds, stateIds, countLines = optionsDetector.predict(zones)
> ```
> 
> Если на входе есть зоны, то на выходе будет столько же елементов в списках
> regionIds, stateIds, countLines
> 
> Если зоны есть а списки пустые, значит вы что-то сделали неправильно, ищите ошибку.

Получается плохо натренилась модель mask_rcnn_numberplate_0100.h5 ?

**Comment by flash1nho** [comment]
Все, нашел ошибку у себя, извиняюсь, все ок - отрабатывает и возвращает ['ru']
