### ISSUE TITLE
Недопустимая инструкция

### ISSUE THREAD

**Issue by Mostalk** [ria-com/nomeroff-net#62]
В чем может быть проблема, устанавливал по инструкции 

root@Server:nomeroff-net/examples/py# python3 demo0.py
Недопустимая инструкция
root@Server:nomeroff-net/examples/py# uname -a
Linux Server 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux

**Comment by dimabendera** [comment]
Убедитесь что у вас установле python3
```
python3 -V
```
или
```
python -V
```
если ваш python3 может имеет алиас python

**Comment by BorisBochkaryov** [comment]
У меня была такая проблема из-за того, что CPU не поддерживает AVX команды, на которых основывается часть оптимизаций Tensorflow.
Предлагаю посмотреть спецификацию вашего CPU и подобрать необходимую сборку tensorflow: https://github.com/evdcush/TensorFlow-wheels 
Внимательно смотрите на версию OS и Python.
