### ISSUE TITLE
Как ещё сократить время распознавания номера?

### ISSUE THREAD

**Issue by cyberman-lab** [ria-com/nomeroff-net#65]
Добрый день.
Мы тестируем вашу систему в нашей организации, цель - реализовать автоматическое управление шлагбаумами на основе БД номеров авто.
Для этих целей мы собрали небольшой сервер на Windows 10, core i5 6-го поколения, 8 Гб DRAM и Nvidia GeForce 2070 super.
Первое распознавание происходит за 7-8 секунд, потом в цикле примерно 2 секунды.
У вас указано 0,5 секунды на видеокарте. Подскажите, какие железки вы используете для достижения такого результата?  И что можно сделать нам для сокращения времени распознавания до заветных 0,5 секунды?

**Comment by ApelSYN** [comment]
1. 0,5 на хорошем железе при условии что вы не запускаете наш скрипт при каждом распознавании, а "обернете" код в виде сервиса, к котрому можно обращаться, например по http или https и получать ответ в формате json или xml. С сервисом также можно взаимодействовать через брокер очередей RabbitMQ или Apache Kafka.

2. Самая "тяжелая" операция это загрузка модели, поэтому если систему организовать в виде сервиса, который стартует, загружает веса модели в видеоплату и далее получает задачи на распознавание, то тогда вся производительность упирается в размер фото, подаваемого на вход, чем меньше размер тем легче все запустить но тем меньше качество. Найдите свой баланс.

3. В качестве "скелета" для микросервиса можно взять фреймворк tornado, flask, ...

4. Поскольку у вас размешение камеры стационарное и угол наклона номера у целевого авто постоянный, вы можете использовать более простые (легкие подходы к расспознаванию), наш алгоритм расчитан на произвольное фото, с произвольным углом съемки, поэтому все так "тяжело".

**Comment by ApelSYN** [comment]
Также мы работаем над версией Nomeroff Net, в которой для поиска маски используется более скоростная сеть Centermask2, там время детекции ускорено приблизительно в 3 раза:
https://github.com/ria-com/nomeroff-net/tree/centermask2
