### ISSUE TITLE
Точность

### ISSUE THREAD

**Issue by machanics** [ria-com/nomeroff-net#74]
Есть ли функция которая будет возвращать точность распознавания  в процентах?

**Comment by ApelSYN** [comment]
Не совсем понятем ваш вопрос. Точность нужно мерять самому на Вашем датасете. 
Условно говоря вы берете 100 фотографий, сами определяете и записываете правильные значения номера (номеров) , распознаете эти 100 фото с помощью нашего модуля и меряете количество правильных ответов в процентах.
Если речь идет о уверенности модели в результате то тут тоже надо уточнять какую именно модель анализируем. В Nomeroff Net, в стандартном варианте использования 3 нейронки:

1. MaskRCNN, которая определяет зоны с номерами, котороые, в дальнейшем, будут распознаваться.
2. Классификатор зон, который определяет какой страны номер, замазан ли номер, сколько линий с текстом на номере
3. Набор ситстем OCR для разных типов номеров и разных стран, у каждой OCR своя точность.

На данных сайта AUTO.RIA.com для украинских номеров у нас процент правильно распозщнаных номеров составляет 97-98% (из тех которые визуально может прочитать человек).

На ваших данных, этот показатель может быть другим.

**Comment by machanics** [comment]
Доброго дня, наверно не совсем правильно поставил вопрос, речь идет о OCR, хотелось бы получать не только распознанный номер (A001PA135) но и ( уверенность / точность ) в нем, что бы была возможность отбрасывать варианты в которых скрипт не уверен например на 95 %

Распознан как A001PA135
![39484fd8-2342-11ea-ac10-90e2ba52560d_0](https://user-images.githubusercontent.com/17236879/77144799-e0a90280-6a97-11ea-9d46-5419ca40d8fd.jpg)
Распознан как A001PA134
![327f35f2-2344-11ea-ac10-90e2ba52560d_0](https://user-images.githubusercontent.com/17236879/77144801-e30b5c80-6a97-11ea-9986-f3a0da228894.jpg)

**Comment by ApelSYN** [comment]
В нашем коде есть переменная в которую поступает вероятность нахождения символа на заданой позиции. Там можно по разному считать  общий результат, можете с єтим поєкспериментировать самостоятельно и возвращать себе обобщенній результат. Мы это не реализовывали. 
Посмотрите переменную **net_out_value**

https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/Base/OCR.py
```python
    def predict(self, imgs, *argv):
        Xs = []
        for img in imgs:
            x = self.normalize(img)
            Xs.append(x)
        pred_texts = []
        if bool(Xs):
            net_out_value = self.MODEL.predict(np.array(Xs))
            #print(net_out_value)
            pred_texts = self.decode_batch(net_out_value)
        return pred_texts
```

**Comment by machanics** [comment]
Спасибо за информацию

**Comment by dimabendera** [comment]
Маска
```python3
NP = nnet.detect([resized_img])
print("[INFO] MASK SCORE:", [np["scores"] for np in NP])
```
Классификатор
```python3
regionIds, stateIds, countLines, classification_score = optionsDetector.predict(zones, return_acc=True)
print("[INFO] CLASSIFICATION SCORE:", classification_score)
```
Нахождение текста
```python3
textArr, ocr_score = textDetector.predict(zones, regionNames, countLines, return_acc=True)
print("[INFO] OKR SCORE:", ocr_score)
```

**Comment by fedExpress** [comment]
> В нашем коде есть переменная в которую поступает вероятность нахождения символа на заданой позиции. Там можно по разному считать общий результат, можете с этим поэкспериментировать самостоятельно и возвращать себе обобщенный результат. Мы это не реализовывали.
> Посмотрите переменную **net_out_value**
> 
> https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/Base/OCR.py
> 
> ```python
>     def predict(self, imgs, *argv):
>         Xs = []
>         for img in imgs:
>             x = self.normalize(img)
>             Xs.append(x)
>         pred_texts = []
>         if bool(Xs):
>             net_out_value = self.MODEL.predict(np.array(Xs))
>             #print(net_out_value)
>             pred_texts = self.decode_batch(net_out_value)
>         return pred_texts
> ```
> 
> Думаю, что со временем, мы проапдейтим эту часть кода таким образом чтоб можно было проанализировать вероятности по каждому распознаному символу.

Добрый день.
Такой вопрос: каким образом можно расчитать общий результат вероятности?
