### ISSUE TITLE
Проблема с .h5 файлами - Google App Engine

### ISSUE THREAD

**Issue by MyhalehaP** [ria-com/nomeroff-net#78]
Здравствуйте!

Есть API на Flask. Пытаюсь задеплоить на Google Cloud, точнее Google App Engine. Использую кастомный рантайм: dockerfile с установкой всех зависимостей и в конце запуск gunicorn. Сначала использовал инициализацию через параметр "latest", т.е.` nnet.loadModel("latest")` - аналогично `optionsDetector.load("latest")` и `textDetector.load("latest")`. Но при запуске приложение прогружало первый, самый тяжелый .h5 файл, после чего worker прекращал работу, либо же приложение просто бесконечно долго работало без какого-либо результата.
После нескольких безуспешных изменений, я перешёл к более грубому способу и переместил директиву models в корень директивы проекта и загрузил все вместе с самим проектом, перед этим указав в коде локальный путь, т.е. : `nnet.loadModel('./models/Detector/mrcnn/mask_rcnn_numberplate_1000_2019_10_07.h5')`

`optionsDetector.load('./models/OptionsDetector/simple/numberplate_options_2019_10_07.h5')`

`textDetector.load('./models/TextDetector/eu/anpr_ocr_eu_2-cpu.h5')`

Просто прописав данные строки кода глобально - эффект тот же, что и в начале.
Пробывал описать внутри `if __name__ == '__main__' ` - ничего не получилось.

Я попытался разделить инициализацию каждого файла на отдельный роут, чтобы локализировать проблему и выяснил, что файл для textDetector загружается без проблем. Проблема только в nnet.loadModel() и optionsDetector.load(). 

Код роутов выглядит следующим образом (один роут, как пример): 

```
@app.route('/init1')
def init_model1():
    
    global graph, nnet
    with graph.as_default():
        
        print("FIRST MODEL")
        logging.warning("FIRST MODEL")
        nnet.loadModel('./models/Detector/mrcnn/mask_rcnn_numberplate_1000_2019_10_07.h5')

    return "success1"
```

Весь код приложения оставлю как ссылку на Ideone, чтобы не засорять даную страницу.
https://ideone.com/S3hRZZ

У меня есть два роута: для изображения и для видео - думаю это не принципиально для данной проблемы, так как возникает она на более раннем этапе. При потребности могу скинуть и dockerfile. Возможно, я упускаю какие-нибудь моменты с зависимоcтями или с принципами работы приложения на сервере.

P.S.
Само собой, локально на компьютере все работает и в разных вариантах. 

P.P.S.
Не совсем понимаю каким образом должен работать путь к Mask_RCNN, если устанавливается все в отдельных папках в site-packages.

```
NF_NET_DIR = os.path.join(dirname,'./nomeroff-net')
MASK_RCNN_DIR = os.path.join(NF_NET_DIR, 'Mask_RCNN')
MASK_RCNN_LOG_DIR = os.path.join(NF_NET_DIR, 'logs')
```

**Comment by dimabendera** [comment]
Здраствуйте!
При запуске вашего кода без докера на локальном компьютере и с GPU и без у нас инициализация весов происходит успешно - ваш код работает.

Думаю проблему следует искать в зависимостях
Скиньте пожалуйста ваш dockerfile

**Comment by MyhalehaP** [comment]
@dimabendera 

dockerfile: https://ideone.com/N3T38c
requirements.txt: https://ideone.com/x8A1ow
app.yaml для gcloud: https://ideone.com/Dwkpxe

**Comment by ApelSYN** [comment]
@MyhalehaP С момента постановки вопроса уже утекло много воды, мы избавились от Mask RCNN, Илон Маск запустил в космос пилотируемый корабль и мы поменяли механизм предварительной детекции на [YOLOv5](https://pytorch.org/hub/ultralytics_yolov5/)
Для тикущей версии мы создали несколько примеров запуска Nomeroff Net в виде REST-сервиса:
  * [Nomeroff Net REST api on Flask](https://github.com/ria-com/nomeroff-net/blob/master/examples/py/flask-rest.py)
  * [Nomeroff Net REST api on Torndo](https://github.com/ria-com/nomeroff-net/blob/master/examples/py/flask-rest.py)

Вы можете попробовать эти два скрипта в  Google App Engine, и если с ними будут проблемы мы попробуем в этом разобраться.

А пока что я навожу порядок в issues.
