### ISSUE TITLE
Проблема с точностью OCR для eu-ua-2015

### ISSUE THREAD

**Issue by opengs** [ria-com/nomeroff-net#79]
Проблема с точностью OCR для украинских номеров eu-ua-2015

Проблема была замечена в демке https://nomeroff.net.ua/onlinedemo.html

С 2013 года появились новые номера с буквой К. Так например для киевского региона появились номера типа КА1234АА. При попытке распознать номера, точность падает до ~5% и почти всегда выдает “АА” вместо “КА”.
Попробовал уже много фотографий но результат тот же.

Вот для примера фото с интернета, чтобы попробовать:
![numberK2](https://user-images.githubusercontent.com/34212339/86452396-8a955d80-bd1c-11ea-8c26-42c01b062e5b.jpg)

И результат демки:
![result](https://user-images.githubusercontent.com/34212339/86452884-40f94280-bd1d-11ea-9618-09938abc66aa.png)

В случаях где нету "К" в номере - работает очень хорошо (около 98% точности)

**Comment by ApelSYN** [comment]
Спасибо за обращение. 
Есть ли у вас образцы фото на которых есть номера с таким сочетанием букв, можно было бы сделать переобучение модели и пофиксить проблему?
В любом случае мы начнем собирать датасет с такими номерами того чтоб в будущем эту поблему пофиксить.

**Comment by opengs** [comment]
К сожалению у меня немного образцов. Осталось совсем несколько. Возможно Вам пригодиться для датасета: [K-numberplates.zip](https://github.com/ria-com/nomeroff-net/files/4877581/K-numberplates.zip). Есть ли у Вас прогнозы, сколько времени уйдет на сборку датасета и тренировку модели?

**Comment by ApelSYN** [comment]
Мы уже собрали датасет. На этой неделе перетренируем модель.
