### ISSUE TITLE
Ошибка при установки

### ISSUE THREAD

**Issue by connected201** [ria-com/nomeroff-net#8]
Добрый день, для теста попробовал установить в докер (дебиан) после выполнения всех перечисленных команд, 
pip3 install -r requirements.txt
выдало ошибку
https://i.imgur.com/T1DR5dY.png
полный лог консоли:
[log.txt](https://github.com/ria-com/nomeroff-net/files/2992403/log.txt)

**Comment by ApelSYN** [comment]
Проект работает с python >= 3.5, поэтому нужно 
не так  
```bash
pip install cython
```
а так 
```bash
pip3 install cython
```
Ну и все остальное ставить через pip3

**Comment by connected201** [comment]
pip3 install cython
сделал и так, но установил и для 2 версии питона!

**Comment by connected201** [comment]
сделал по новой, без установки 2 версии питона, результат тот же, попробую на полноценную версию дебиан в виартуалке, отпишусь после результатов!

**Comment by connected201** [comment]
в нормальной виртуалке, всё установилось без проблем! извините за беспокойство!
