### ISSUE TITLE
OCR Moderation Не определяет номера на картинке

### ISSUE THREAD

**Issue by prozaklob** [ria-com/nomeroff-net#82]
Доброго времени суток!
Запустил ноду
ошибок нет
в директорию dataset закинул 2 папки: img,ann.
в папку im закинул картинки.
При открытии веб морды ошибок нода не высыпает.

```
nomeroff-net listening at port 5005
  <-- GET /OCRM.html
  --> GET /OCRM.html 200 11ms 15.65kb
  <-- POST /regionOCRModeration
{
  tags: [],
  objects: [],
  state_id: 0,
  region_id: 0,
  size: { width: 0, height: 0 },
  moderation: { isModerated: 0, moderatedBy: 'dimabendera', predicted: '' }
}
{
  img_path: 'img/dasdsadsa.JPG',
  name: 'dasdsadsa',
  predicted: '',
  description: undefined
}
{
  img_path: 'img/fdsfsd.JPG',
  name: 'fdsfsd',
  predicted: '',
  description: undefined
}
___________________
  --> POST /regionOCRModeration 200 6ms 471b
  <-- GET /img/dasdsadsa.JPG
  <-- GET /img/fdsfsd.JPG
  --> GET /img/dasdsadsa.JPG 200 3ms 12.76kb
  --> GET /img/fdsfsd.JPG 200 3ms 10.89kb
```

В веб интерфейсе номера не распознаются.
Над номером прочерк.
xx-unknown
garbage
count_lines

при нажатии save & load next

```
{
  tags: [],
  objects: [],
  state_id: 0,
  region_id: 0,
  size: { width: 0, height: 0 },
  moderation: { isModerated: 0, moderatedBy: 'dimabendera', predicted: '' }
}
{
  img_path: 'img/dasdsadsa.JPG',
  name: 'dasdsadsa',
  predicted: '',
  description: undefined
}
{
  img_path: 'img/fdsfsd.JPG',
  name: 'fdsfsd',
  predicted: '',
  description: undefined
}
___________________
```

**Comment by ApelSYN** [comment]
Фоомат должен быть png

сб, 11 лип. 2020, 03:16 користувач prozaklob <notifications@github.com>
пише:

**Comment by prozaklob** [comment]
> Фоомат должен быть png 

{
  img_path: 'img/dasdsadsa.png',
  name: 'dasdsadsa',
  predicted: '',
  description: undefined
}

Эффект тот же.

**Comment by ApelSYN** [comment]
Вначале невнимательно прочитал вопрос.
Номера а админке не должны распознаваться, эта админка как раз и преднаначена для разметки данных (для дальнейшего обучения) а не наоборот. 
Чтоб добыть из обычных фото потенциальные области с написанием номеров нужно доработать под себя вот этот скрипт:
https://github.com/ria-com/nomeroff-net/blob/master/tools/avto-nomer-tool/py/avto-nomer_grab.ipynb

**Comment by prozaklob** [comment]
да,спасибо. Разобрался. К счастью не понадобилось. Беларуские номера распознает как два пальца.
Остался вопрос с производительностью. Если через cv2 дергать фреймы с потока и в цикле детектить - модель остается подгруженой. на gpu меньше секунды на номер.(можно и быстрее ).
Уперся в производительность самого cv. Сильно тормознутый.
