### ISSUE TITLE
Скорость загрузки библиотек и модели

### ISSUE THREAD

**Issue by romanjkeey** [ria-com/nomeroff-net#84]
Здравствуйте. 
Я запускаю вашу программу не через Юпитер, а через командную строку .py
Время распознавание достигает 36 секунд, что, достаточно долго, из-за того, что каждый раз загружаются библиотеки и т.д.
Можно как - то сделать так, что бы запустить один раз модели и библиотеки, и дальнейшее распознавание было быстрее?
Спасибо

**Comment by ApelSYN** [comment]
Почитайте эти ветки:
https://github.com/ria-com/nomeroff-net/issues/65
https://github.com/ria-com/nomeroff-net/issues/69
