### ISSUE TITLE
Проблема с tensorflow 2.2.0

### ISSUE THREAD

**Issue by pashey173** [ria-com/nomeroff-net#91]
Здравствуйте. Пытаюсь запустить Ваш код на tensorflow 2.2.0, вылетает ошибка:

AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

Возможно ли каким - то образом запустить demo3 на версии 2.2.0?

И как запустить файл demo3 с использованием GPU?
Спасибо.

**Comment by ApelSYN** [comment]
Там будем множество несовместимх строчек. Если нет возможности поставить tensorflow 1.5.x, запускайте в docker-е

**Comment by pashey173** [comment]
Я уже поставил 1.15.2
Запускается на CPU, но если пытаюсь запустить на GPU, то выходит ошибка

Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [[{{node conv1/convolution}}]] [[mrcnn_detection/Reshape_1/_5635]]

Хотелось бы запустить все - таки на GPU.
Проверил работоспособность GPU с NVIDIA и CUDA
Везде True

**Comment by ApelSYN** [comment]
Tensorflow модет быть собран под устаревшуюю cuda. Поробуйте сами собрать
tf по инструкции
https://www.tensorflow.org/install/source

сб, 25 лип. 2020, 15:32 користувач pashey173 <notifications@github.com>
пише:

**Comment by pashey173** [comment]
Нужно что - то добавлять в коде, что бы ускорить процесс загрузки модели и т.д. с использованием GPU?

**Comment by ApelSYN** [comment]
В память GPU модель груится немного дольше чем в ОЗУ, ускорение происходит на этапе инференса. Ускорить рботу можно написав обертку в виде сервиса. Посмотрите другие issues, там уже про это спрашивали и отвечали неоднократно, [тут я уже овечал на этот вопрос](https://github.com/ria-com/nomeroff-net/issues/84)

**Comment by ApelSYN** [comment]
Уже есть бета для TensorFlow 2.x без Mask RCNN, можете пробовать:
https://github.com/ria-com/nomeroff-net/tree/v1.0

**Comment by ApelSYN** [comment]
Уточнение -- модели натренированы для **tensorflow >=2.3**
