### ISSUE TITLE
Очень низкий процент распознавания

### ISSUE THREAD

**Issue by cyberman-lab** [ria-com/nomeroff-net#93]
Камеры RVi-IPC44 V.2
Поток 25fps 1920x1080
VGA NV GF 2070 SUPER
Установлена задержка в 0,1 сек в цикле поиска рамок
Скриншотил наши логи, на разрешение не нужно обращать внимание.

![Screenshot_4](https://user-images.githubusercontent.com/61228772/89161370-354aa700-d57b-11ea-936f-09ee382ab0f2.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/61228772/89161372-367bd400-d57b-11ea-99bf-2cd837daeb99.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/61228772/89161376-37146a80-d57b-11ea-9ab5-96128c497818.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/61228772/89161379-37146a80-d57b-11ea-9f47-5c5899b7ea34.jpg)

Процент правильных распознаваний около 70, точнее сказать сложно, так как приходится руками искать.
Вопрос: что мы не так делаем?

**Comment by ApelSYN** [comment]
Качество фотографий, на первый взгляд, хорошее.
То что сразу бросается в глаза -- мы тренировали модель где площадь номера гораздо меньше, на сайте http://AUTO.RIA.com размещают фото, где скорее всего видно все авто, и поэтому скорее всего происходит некачественная детекция рамки. Чтоб существенно повысить качество, нужно переразметить датесет для mask-rcnn, где правильно нарисовать рамки для таких как у вас ракурсов, это однозначно улучшит качество. Далее -- перетренировать модель.
Если вы готовы к такому виду работ, то мы обязательно ответим на любые ваши вопросы, которые возникнут во время разметки и во время тренировки.

**Comment by cyberman-lab** [comment]
Я неправильно предоставил скриншоты, это лишь обрезанная часть для нашей лог-системы
. Ниже примеры кадров, с которых происходит распознавание. 
![photo_2020-07-31_19-25-24](https://user-images.githubusercontent.com/61228772/89176943-24a62b00-d593-11ea-8e4e-f59d91135d10.jpg)
![photo_2020-07-31_19-27-42](https://user-images.githubusercontent.com/61228772/89176946-253ec180-d593-11ea-9add-752e24575084.jpg)

**Comment by ApelSYN** [comment]
Пришлите пару десятков "проблемных" фото -- посмотрим можно ли что-то с єтим сделать.

**Comment by cyberman-lab** [comment]
Мы разобрались в чем была проблема:
оказывается у нас на распознавание отправлялся не оригинальный скриншот в 1920х1080, а обрезанный до 640 на 400 с чем-то.

**Comment by cyberman-lab** [comment]
Проблема решена, распознавание снова допускает очень мало ошибок. Ещё раз спасибо за ваши труды!
