### ISSUE TITLE
можно ли сделать трейн с другими номерами?

### ISSUE THREAD

**Issue by aisamang** [ria-com/nomeroff-net#94]
Здравствуйте! Всё очень хорошо распознает, но в Казахстане есть номера красного цвета и у них расклад цифр и букв другая. Красные номера не может распознать, даже если они казахстанские. Пожалуйста подскажите что можно
сделать? 
![040497624](https://user-images.githubusercontent.com/53483096/90853369-c0a9a200-e39b-11ea-9d68-bc6ac2f5e784.JPG)

**Comment by ApelSYN** [comment]
Нужен датасет (фото машин), где есть такие номера, их можно разметить и распознавать. К сотжалению, у нас нету доступа к таким датасетам.
