### ISSUE TITLE
Проблема с установкой

### ISSUE THREAD

**Issue by EndErr** [ria-com/nomeroff-net#95]
#47 тот же случай только в моем случае не помогает замена версии tensorflow na 1.14.0.
`  Could not find a version that satisfies the requirement tensorflow==1.14.0 (from -r requirements.txt (line 7)) (from versions: )
No matching distribution found for tensorflow==1.14.0 (from -r requirements.txt (line 7))
`

**Comment by ApelSYN** [comment]
Вам пишет что нет такой сборки в репозитории для вашей системы. Можете попробовать 1.15.2 или 1.15.3 єто саміе свежие версии для tensorflow 1. Сейчас, к сожалению, эта версия не развивается.
В скором будущем мы планируем выложить версию для tensorflow 2.x и с заменой Mask RCNN на более скоростую систему нахождения области номера -- следите за анносами.

**Comment by EndErr** [comment]
Пытаюсь прикрутить вашу работу на Jetson Nano,  все установилось, tensorflow 1.15.3 взял из ресурсов Nvidia.
Но вот другая проблемма, при запуске demo выдает такие бесконечные ошибки и не могу остановить процесс

> 2020-08-27 09:09:20.224685: W tensorflow/core/common_runtime/bfc_allocator.cc:424] *************************************************xx**********_______________________________________
> 2020-08-27 09:09:30.225111: W tensorflow/core/common_runtime/bfc_allocator.cc:419] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.15GiB (rounded to 1234173952).  Current allocation summary follows.
> 2020-08-27 09:09:30.225225: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (256):   Total Chunks: 112, Chunks in use: 111. 28.0KiB allocated for chunks. 27.8KiB in use in bin. 9.8KiB client-requested in use in bin.
> 2020-08-27 09:09:30.225308: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (512):   Total Chunks: 42, Chunks in use: 42. 21.0KiB allocated for chunks. 21.0KiB in use in bin. 21.0KiB client-requested in use in bin.
> ...
> 2020-08-27 09:09:30.225879: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (134217728):     Total Chunks: 0, Chunks in use: 0. 0B allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
> 2020-08-27 09:09:30.225912: I tensorflow/core/common_runtime/bfc_allocator.cc:869] Bin (268435456):     Total Chunks: 1, Chunks in use: 0. 271.11MiB allocated for chunks. 0B in use in bin. 0B client-requested in use in bin.
> 2020-08-27 09:09:30.225945: I tensorflow/core/common_runtime/bfc_allocator.cc:885] Bin for 1.15GiB was 256.00MiB, Chunk State:
> 2020-08-27 09:09:30.225985: I tensorflow/core/common_runtime/bfc_allocator.cc:891]   Size: 271.11MiB | Requested Size: 22.25MiB | in_use: 0 | bin_num: 20, prev:   Size: 64.00MiB | Requested Size: 64.00MiB | in_use: 1 | bin_num: -1
> 2020-08-27 09:09:30.226014: I tensorflow/core/common_runtime/bfc_allocator.cc:898] Next region of size 728006656
> 2020-08-27 09:09:30.226040: I tensorflow/core/common_runtime/bfc_allocator.cc:905] InUse at 0xf00d10000 next 1 of size 1280
> 2020-08-27 09:09:30.226067: I tensorflow/core/common_runtime/bfc_allocator.cc:905] InUse at 0xf00d10500 next 2 of size 256
> ...
> 2020-08-27 09:09:30.245938: I tensorflow/core/common_runtime/bfc_allocator.cc:905] InUse at 0xf1743b600 next 1029 of size 67108864
> 2020-08-27 09:09:30.245965: I tensorflow/core/common_runtime/bfc_allocator.cc:905] Free  at 0xf1b43b600 next 18446744073709551615 of size 284281344
> 2020-08-27 09:09:30.245989: I tensorflow/core/common_runtime/bfc_allocator.cc:914]      Summary of in-use Chunks by size:
> 2020-08-27 09:09:30.246027: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 111 Chunks of size 256 totalling 27.8KiB
> 2020-08-27 09:09:30.246057: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 42 Chunks of size 512 totalling 21.0KiB
> ...
> 2020-08-27 09:09:30.246957: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 56360448 totalling 53.75MiB
> 2020-08-27 09:09:30.246985: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 67108864 totalling 64.00MiB
> 2020-08-27 09:09:30.247013: I tensorflow/core/common_runtime/bfc_allocator.cc:921] Sum Total of in-use chunks: 421.13MiB
> 2020-08-27 09:09:30.247038: I tensorflow/core/common_runtime/bfc_allocator.cc:923] total_region_allocated_bytes_: 728006656 memory_limit_: 728006656 available bytes: 0 curr_region_allocation_bytes_: 1456013312
> 2020-08-27 09:09:30.247073: I tensorflow/core/common_runtime/bfc_allocator.cc:929] Stats:
> Limit:                   728006656
> InUse:                   441585920
> MaxInUse:                725867264
> NumAllocs:                    2550
> MaxAllocSize:            284281344

В интернете пишут что надо добавить этот код но не могу понять где его добавить

> 
> import tensorflow as tf
> config = tf.ConfigProto()
> config.gpu_options.allow_growth = True
> sess = tf.Session(config=config)

**Comment by ApelSYN** [comment]
У Вас нехватает памяти на GPU. Эти строки пишутся в начале скрипта, только Jetson Nano это не поможет, т.к. суммарно скрипт использует более 5G видеопамяти, а у Вас доступно 4G (если я не ошибаюсь). Ожидайте выхода нашей новой версии, она будет менее прожерливой и более экономной к ресурсам.

**Comment by EndErr** [comment]
> Ожидайте выхода нашей новой версии, она будет менее прожерливой и более экономной к ресурсам.
Есть предположение когда это будет?

**Comment by ApelSYN** [comment]
Код в бете уже доступен в ветке v1.0:
https://github.com/ria-com/nomeroff-net/tree/v1.0

Там Mask RCNN замене на [centermask2](https://github.com/youngwanLEE/centermask2), с легким бекндом и OCR построен на tensorflow2. 

Это бета которая постоянно дорабатывается, так что относитесь к ней как к бете и шлите багрепорты.
