### ISSUE TITLE
ValueError: Unknown layer: Functional

### ISSUE THREAD

**Issue by EndErr** [ria-com/nomeroff-net#97]
Установил v1.0 но выдает ошибку при загрузке моделей.
`ValueError: Unknown layer: Functional`

**Comment by ApelSYN** [comment]
Этого недостаточно чтоб понять причину проблемы. Какая версия всего на чем стартуете, какое железо и т.д.

**Comment by EndErr** [comment]
Установил на Nvidia Jetson Nano, установка прошла успешно со всеми requirements-ами.
При запуске примера с страницы для 1.0 все модели скачиваются по "latest", `nnet.loadModel(NOMEROFF_NET_DIR)` загружает все нормально а вот `optionsDetector.load("latest")` и `textDetector.load("latest")` после скачивания не загружаются.

> tensorflow 2.2.0+nv20.7
> torch 1.6.0
> torchvision 0.7.0a0+78ed10c
> Keras 2.2.5
> detectron2 0.2.1

Проблем с памятью в Jetson-е нет как с предыдущей версией.

**Comment by ApelSYN** [comment]
У меня есть дома Jetson Xavier.
Я попробую на этой неделе туда поставить 1.0, ПО там аналогичное, но железо
немного помощнее и больше RAM-а. Думаю, что после такого эксперимента смогу
вам оиветить.

вт, 1 вер. 2020, 12:02 користувач Negruzzi Cristian <
notifications@github.com> пише:

**Comment by ApelSYN** [comment]
Та же ошибка на Jetson Xavier. Пока что причина мне непонятна. Возможно проблема возникает потому что эта модель натренирована на tensorflow 2.3, а для Jetson пока что доступна версия 2.2.
На  сл. неделе поэкспериментрую с этим.

**Comment by EndErr** [comment]
Вот что нашел в поиске:
[https://github.com/tensorflow/tensorflow/issues/41929](url)
[https://stackoverflow.com/questions/63068639/valueerror-unknown-layer-functional](url)

**Comment by ApelSYN** [comment]
Это точно из-за версии tensorflow, у меня тожк самое в докере если ставить версию ниже 2.3. Заморачиваться с конвертацией нету смысла лучше перетренировать модели на старой версии. Пока что у меня на это нету времени, т.к. у нас везде свежий tensorflow. Можете провести тренировку самостоятельно, вот тут скрипты
https://github.com/ria-com/nomeroff-net/tree/v1.0/train
Для начала https://github.com/ria-com/nomeroff-net/blob/v1.0/train/options.ipynb, потом те страны, для которых будете использовать модели. Датасеты мы все что есть выложили https://nomeroff.net.ua/datasets/.

**Comment by ApelSYN** [comment]
Кстати, памяти все загруженные модели потребляют около 4.5G, можно заоптимизировать tensorflow-модели с помощью TensorRT, который есть для Jetson Nano и тогда, судя-по всему, все влезет.

**Comment by EndErr** [comment]
Спасибо, по пробую уже в понедельник.

**Comment by ApelSYN** [comment]
Не забудьте добавить вначало кода:
```python
from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)```

**Comment by ApelSYN** [comment]
Натренировал 2 модели для Jetson на базе tensorflow 2.2 ,  (минимум для того чтоб заработал пример hello). У меня все заработало -- номера распознались.
Для того чтоб подгрузить модели для 2.2, меняем в [**NomeroffNet/mcm/latest.py**](https://github.com/ria-com/nomeroff-net/blob/master/NomeroffNet/mcm/latest.py) адреса загрузки моделей
```python
  #...
  "OptionsDetector": {
    "simple": {
      "h5": {
        "class_region": [
          "xx_unknown",
          "eu_ua_2015",
          "eu_ua_2004",
          "eu_ua_1995",
          "eu",
          "xx_transit",
          "ru",
          "kz",
          "eu-ua-fake-dnr",
          "eu-ua-fake-lnr",
          "ge"
        ],
        "gpu": "https://nomeroff.net.ua/models/options/tf2.2/numberplate_options_2020_08_20_tensorflow_v2.2.h5",
        "cpu": "https://nomeroff.net.ua/models/options/tf2.2/numberplate_options_2020_08_20_tensorflow_v2.2.h5"
      }
    }
  },
  #...
  "TextDetector": {
    #...
    "eu": {
      "h5": {
        "cpu": "https://nomeroff.net.ua/models/ocr/eu/tf2.2/anpr_ocr_eu_2020_09_07_tensorflow_v2.2.h5",
        "gpu": "https://nomeroff.net.ua/models/ocr/eu/tf2.2/anpr_ocr_eu_2020_09_07_tensorflow_v2.2.h5"
      }
    },
   #...
  }
```
Также на ARM есть особенность запуска  OpenCV, его надо грузить первым, и еще ставить ограничение памяти для tensorflow, начало примера должно выглядеть приблизительно так:
```
import os
import cv2
os.environ["CUDA_VISIBLE_DEVICES"] = "0" 

from tensorflow.compat.v1 import ConfigProto
from tensorflow.compat.v1 import InteractiveSession

config = ConfigProto()
config.gpu_options.allow_growth = True
session = InteractiveSession(config=config)
#...
```
Были проблемы со сборкой imgaug, решил таким образом: собрал вежий OpenCV этим скриптом:
https://github.com/JetsonHacksNano/buildOpenCV
потом скачал с github-а свежий imgaug и закоментровал скроку c **opencv-python-headless** в INSTALL_REQUIRES  файла **setup.py**
Затем ставим:
```sh
apt-get install libgeos-dev
cd imgaug
python3 setup.py install
```

Ограничения по памяти я не проверял, на Jetson Xavier ее много, но у вас может нехватить. 
Как я уже и писал, проблему может решить приминение TensorRT как и для ускорения так и для экономии памяти.

**Comment by ApelSYN** [comment]
Залил все модели для Jetson Xavier, запустил [бенчмарк](https://github.com/ria-com/nomeroff-net/blob/v1.0/banchmarks/runtime.ipynb), результат неплохой **871** ms/фото:
```
Processed 260 photos
Time 226.3975555896759
One photo process 0.8707598291910612 seconds
```
Конфиг для tensorflow 2.2 **[NomeroffNet/mcm/latest-tf2.2.py](https://github.com/ria-com/nomeroff-net/blob/v1.0/NomeroffNet/mcm/latest-tf2.2.py)**, его надо скопировать в **[NomeroffNet/mcm/latest.py](https://github.com/ria-com/nomeroff-net/blob/v1.0/NomeroffNet/mcm/latest.py)**

**Comment by EndErr** [comment]
На Jetson Nano тоже все работает но надо всетаки через TensorRT прогнать модели, но пока не знаю как, сейчас занимает всю память и повышение свопа не помогает.

**Comment by ApelSYN** [comment]
Мы с Дмитрием сможем это попробовать на сл. неделе, там есть риск незначительного ухудшение точности, но это десятые процента, думаю для наших задач это допустимо.

**Comment by SergeyLev** [comment]
> На Jetson Nano тоже все работает но надо всетаки через TensorRT прогнать модели, но пока не знаю как, сейчас занимает всю память и повышение свопа не помогает.

Я сейчас пишу конвертатор OCR. Когда закончу залью.

**Comment by SergeyLev** [comment]
@EndErr #138
